#
#     /\_____/\
#    /  o   o  \
#   ( ==  ^  == )
#    )         (
#   (           )
#  ( (  )   (  ) )
# (__(__)___(__)__)
#
# Installation:
#   poetry install
#
# References:
#   - pyproject.toml: https://packaging.python.org/en/latest/
#   - poetry        : https://python-poetry.org/docs/
#   - uv            : https://docs.astral.sh/uv/

[project]
name            = "aic26_06"
version         = "0.1.0"
description     = "AI City Challenge 2026 - Track 06: Cross-City Object Detection"
license         = "MIT"
readme          = "README.md"
requires-python = ">=3.13,<3.14"
authors         = [{ name = "Long H. Pham", email = "longpham3105@gmail.com" }]
keywords        = ["computer vision", "deep learning", "research"]
classifiers     = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
]
dependencies    = ["mon"]

# [project.urls]
# Homepage      = ""
# Documentation = ""
# Repository    = ""
# Issues        = ""

# --- UV SPECIFIC ---
[tool.uv]
package = true
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'"
]

[tool.uv.sources]
mon = { workspace = true }

# --- POETRY SPECIFIC ---
[tool.poetry]
# package-mode = false                    # If you want to use Poetry only for dependency management but not for packaging.
packages = [
    { include = "edgecrafter", from = "src" }
]
include  = []
exclude  = []

[tool.poetry.dependencies]
mon = { path = "../../libs/mon", develop = true }

[build-system]
requires      = ["poetry-core>=2.3.2,<3.0.0"]
build-backend = "poetry.core.masonry.api"
