dataset: lol_v1

#### datasets
datasets:
  train:
    dist       : False
    root       : llie/lol_v1
    use_shuffle: true
    n_workers  : 1
    batch_size : 8
    use_flip   : true
    use_crop   : true
    patch_size : 96
    sub_data   : train

  val:
    dist      : False
    root      : llie/lol_v1
    n_workers : 1
    use_crop  : true
    batch_size: 1
    sub_data  : test
