# General config
root        :
weights     :
model       :
data        : "lol_v2_real"
fullname    :
save_dir    :
device      : 0
epochs      : 100
steps       :
imgsz       : 384
resize      :
benchmark   :
save_image  :
use_data_dir:
exist_ok    : False
verbose     : True

# Model
loss_weights: [0.35, 0.10, 0.25, 0.30]

# Training
batch_size  : 4
lr          : 0.00001
