#
#     /\_____/\
#    /  o   o  \
#   ( ==  ^  == )
#    )         (
#   (           )
#  ( (  )   (  ) )
# (__(__)___(__)__)
#
# Installation:
#   poetry install --extras "docs gui"
#   or,
#   poetry install --extras "docs"
#
# References:
#   - pyproject.toml: https://packaging.python.org/en/latest/
#   - poetry        : https://python-poetry.org/docs/
#   - uv            : https://docs.astral.sh/uv/

[project]
name            = "mon-workspace"
version         = "2.11.0"
description     = "A monorepo centralizing multiple projects and sharing code."
license         = "MIT"
readme          = "README.md"
requires-python = ">=3.12,<3.14"
authors         = [{ name = "Long H. Pham", email = "longpham3105@gmail.com" }]
keywords        = ["computer vision", "deep learning", "research"]
classifiers     = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
]
dependencies = ["mon", "dev"]

[project.urls]
Homepage      = "https://github.com/phlong3105/mon"
Documentation = "https://github.com/phlong3105/mon/docs"
Repository    = "https://github.com/phlong3105/mon.git"
Issues        = "https://github.com/phlong3105/mon/issues"

[project.optional-dependencies]
docs = [                                # Documentation
    "markdown",                         # Python implementation of Markdown.
    "mkdocs",                           # Project documentation with Markdown.
    "mkdocs-material",                  # A Material Design theme for mkdocs.
    "mkdocstrings",                     # Automatic documentation from sources, for MkDocs.
    "sphinx",                           # Sphinx is a tool that makes it easy to create intelligent and beautiful documentation.
    "sphinx-paramlinks",                # A Sphinx extension which allows :param: directives within Python documentation to be linkable.
]
gui  = [                                # GUI Applications
    "PyQt6",                            # Python bindings for the Qt cross-platform application toolkit.
    "matplotlib",                       # Publication quality figures in Python.
]

# --- UV SPECIFIC ---
[tool.uv]
package = false  # <--- Add this for monorepo roots
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'"
]

[tool.uv.workspace]
members = ["libs/*", "projects/*"]

[tool.uv.sources]
mon = { workspace = true }
dev = { workspace = true }

# --- POETRY SPECIFIC ---
[tool.poetry]
package-mode = false                    # If you want to use Poetry only for dependency management but not for packaging.
# paclage      = [{ include = "", from = "" }]
include      = []
exclude      = []

[tool.poetry.dependencies]
mon = { path = "libs/mon"         , develop = true }
dev = { path = "projects/aic26_01", develop = true }
dev = { path = "projects/aic26_06", develop = true }
dev = { path = "projects/dev"     , develop = true }

[build-system]
requires      = ["poetry-core>=2.3.2,<3.0.0"]
build-backend = "poetry.core.masonry.api"
