_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
#    NORM: syncBN
    NAME: build_resnest_backbone
#  HEADS:
#    NORM: syncBN

DATASETS:
  NAMES: ("CUHKSYSU",)
  TESTS: ("CUHKSYSU",)

OUTPUT_DIR: fast_reid/logs/CUHKSYSU/sbs_S50
