name              : "resnet"
variant           : "resnet18"
zero_init_residual: False
channels          : 3
backbone          : [
  # [from, number, module,            args(out_channels, ...)]
  [-1,     1,      Conv2d,            [64, 7, 2, 3, 1, 1, False]],                                        # 0
  [-1,     1,      BatchNorm2d,       []],                                                                # 1
  [-1,     1,      ReLU,              [True]],                                                            # 2
  [-1,     1,      MaxPool2d,         [3, 2, 1]],                                                         # 3
  [-1,     1,      ResNetBlock,       [ResNetBasicBlock, 2, 64,  64,  1, 1, 1, 64, False, BatchNorm2d]],  # 4
  [-1,     1,      ResNetBlock,       [ResNetBasicBlock, 2, 64,  128, 2, 1, 1, 64, False, BatchNorm2d]],  # 5
  [-1,     1,      ResNetBlock,       [ResNetBasicBlock, 2, 128, 256, 2, 1, 1, 64, False, BatchNorm2d]],  # 6
  [-1,     1,      ResNetBlock,       [ResNetBasicBlock, 2, 256, 512, 2, 1, 1, 64, False, BatchNorm2d]],  # 7
  [-1,     1,      AdaptiveAvgPool2d, [1]],                                                               # 8
]
head              : [
  [-1,     1,      LinearClassifier,  [512]],                                                             # 9
]
