name              : "shufflenet"
variant           : "shufflenet-v2-x2.0"
zero_init_residual: False
channels          : 3
backbone          : [
  # [from, number, module,           args(out_channels, ...)]
  # Stage 1
  [-1,     1,      Conv2d,           [24, 3, 2, 1, 1, 1, False]],    # 0
  [-1,     1,      BatchNorm2d,      [24]],                          # 1
  [-1,     1,      ReLU,             [True]],                        # 2
  [-1,     1,      MaxPool2d,        [3, 2, 1]],                     # 3
  # Stage 2
  [-1,     1,      InvertedResidual, [244, 2]],                      # 4
  [-1,     1,      InvertedResidual, [244, 1]],                      # 5
  [-1,     1,      InvertedResidual, [244, 1]],                      # 6
  [-1,     1,      InvertedResidual, [244, 1]],                      # 7
  # Stage 3
  [-1,     1,      InvertedResidual, [488, 2]],                      # 8
  [-1,     1,      InvertedResidual, [488, 1]],                      # 9
  [-1,     1,      InvertedResidual, [488, 1]],                      # 10
  [-1,     1,      InvertedResidual, [488, 1]],                      # 11
  [-1,     1,      InvertedResidual, [488, 1]],                      # 12
  [-1,     1,      InvertedResidual, [488, 1]],                      # 13
  [-1,     1,      InvertedResidual, [488, 1]],                      # 14
  [-1,     1,      InvertedResidual, [488, 1]],                      # 15
  # Stage 4
  [-1,     1,      InvertedResidual, [976, 2]],                      # 16
  [-1,     1,      InvertedResidual, [976, 1]],                      # 17
  [-1,     1,      InvertedResidual, [976, 1]],                      # 18
  [-1,     1,      InvertedResidual, [976, 1]],                      # 19
  # Stage 5
  [-1,     1,      Conv2d,           [2048, 1, 1, 0, 1, 1, False]],  # 20
  [-1,     1,      BatchNorm2d,      [2048]],                        # 21
  [-1,     1,      ReLU,             [True]],                        # 22
]
head              : [
  [-1,     1,      ShuffleNetV2Classifier, [2048]],                  # 23
]
