name    : "squeezenet"
variant : "squeezenet-1.1"
channels: 3
backbone: [
  # [from, number, module,    args(out_channels, ...)]
  [-1,     1,      Conv2d,    [64, 3, 2]],                 # 0
  [-1,     1,      ReLU,      [True]],                     # 1
  [-1,     1,      MaxPool2d, [3, 2, 0, 1, False, True]],  # 2
  [-1,     1,      Fire,      [64,  16, 64,  64]],         # 3
  [-1,     1,      Fire,      [128, 16, 64,  64]],         # 4
  [-1,     1,      MaxPool2d, [3, 2, 0, 1, False, True]],  # 5
  [-1,     1,      Fire,      [128, 32, 128, 128]],        # 6
  [-1,     1,      Fire,      [256, 32, 128, 128]],        # 7
  [-1,     1,      MaxPool2d, [3, 2, 0, 1, False, True]],  # 8
  [-1,     1,      Fire,      [256, 48, 192, 192]],        # 9
  [-1,     1,      Fire,      [384, 48, 192, 192]],        # 10
  [-1,     1,      Fire,      [384, 64, 256, 256]],        # 11
  [-1,     1,      Fire,      [512, 64, 256, 256]],        # 12
]
head    : [
  [-1,     1,      SqueezeNetClassifier, [512]],           # 13
]
