#
#     /\_____/\
#    /  o   o  \
#   ( ==  ^  == )
#    )         (
#   (           )
#  ( (  )   (  ) )
# (__(__)___(__)__)
#
# Installation:
#   poetry install
#
# References:
#   - pyproject.toml: https://packaging.python.org/en/latest/
#   - poetry        : https://python-poetry.org/docs/

[project]
name            = "mertens_pytorch"
version         = "0.0.1"
authors         = [
    { name = "Long H. Pham", email = "longpham3105@gmail.com" },
]
maintainers     = [
    { name = "Long H. Pham", email = "longpham3105@gmail.com" },
]
description     = "Mertens et. al Exposure Fusion in PyTorch."
readme          = "README.md"
license         = "MIT"
license-files   = ["LICENSE.*"]
keywords        = [
    "computer vision",
    "image processing",
    "deep learning",
    "research",
]
classifiers     = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
]
requires-python = ">=3.12,<3.14"
dependencies    = [
    "mon",
]

[project.urls]
Homepage      = ""
Documentation = ""
Repository    = ""
Issues        = ""

[tool.poetry]
package-mode = false                    # If you want to use Poetry only for dependency management but not for packaging.
# packages = [ { include = "project_abc", from = "." } ]
include  = []
exclude  = []

[tool.poetry.dependencies]
mon = { path = "../../shared/mon", develop = true }

[build-system]
requires      = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
