_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone

DATASETS:
  NAMES: ("CUHKSYSU_DanceTrack",)
  TESTS: ("CUHKSYSU_DanceTrack",)

OUTPUT_DIR: fast_reid/logs/CUHKSYSU_DanceTrack/agw_S50
