_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    WITH_IBN: True

DATASETS:
  NAMES: ("CUHKSYSU_DanceTrack",)
  TESTS: ("CUHKSYSU_DanceTrack",)

OUTPUT_DIR: fast_reid/logs/CUHKSYSU_DanceTrack/bagtricks_R50-ibn
