_BASE_: ../Base-MGN.yml

MODEL:
  BACKBONE:
    WITH_IBN: True
  HEADS:
    EMBEDDING_DIM: 64     # 256 to 64

DATASETS:
  NAMES: ("CUHKSYSU_DanceTrack",)
  TESTS: ("CUHKSYSU_DanceTrack",)

OUTPUT_DIR: fast_reid/logs/CUHKSYSU_DanceTrack/mgn_R50-ibn
