_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True

DATASETS:
  NAMES: ("DanceTrack",)
  TESTS: ("DanceTrack",)

OUTPUT_DIR: fast_reid/logs/dancetrack/bagtricks_R101-ibn
