# General config
root        :
weights     :
data        :
model       :
fullname    :
save_dir    :
device      : 0
epochs      : 400
steps       :
imgsz       : 512
resize      :
benchmark   :
save_image  :
use_data_dir:
exist_ok    : False
verbose     : True

# Model

# Training
