_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
#    NORM: syncBN
#  HEADS:
#    NORM: syncBN
#SOLVER:
#  IMS_PER_BATCH: 256

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/sbs_S50
