task: pose

model: ECPose
criterion: DETRPoseCriterion
postprocessor: DETRPosePostProcessor

use_focal_loss: True
eval_spatial_size: [640, 640] # h w
checkpoint_freq: 4    # save freq
grad_accum_steps: 1

ECPose:
  backbone: ViTAdapter
  encoder: HybridEncoder
  decoder: DETRTransformer


HybridEncoder:
  in_channels: [192, 192, 192]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.

  # cross
  expansion: 1.0
  depth_mult: 1
  act: silu

  # New
  csp_type: csp2
  fuse_op: sum


DETRTransformer:
  hidden_dim: 256
  dropout: 0.0
  nhead: 8
  num_queries: 60
  dim_feedforward: 1024
  num_decoder_layers: 6
  normalize_before: False
  return_intermediate_dec: True
  activation: 'relu'
  num_feature_levels: 3
  dec_n_points: 4
  learnable_tgt_init: True
  two_stage_type: 'standard'
  num_body_points: 17
  aux_loss: True
  dec_pred_class_embed_share: False
  dec_pred_pose_embed_share: False
  two_stage_class_embed_share: False
  two_stage_bbox_embed_share: False
  cls_no_bias: False
  feat_strides: [8, 16, 32]
  reg_max: 32
  reg_scale: 4


DETRPoseCriterion:
  num_classes: 2
  weight_dict: {loss_vfl: 2.0, loss_keypoints: 10.0, loss_oks: 4.0}
  focal_alpha: 0.25
  losses: ['vfl', 'keypoints']
  matcher:
    type: DETRPoseHungarianMatcher
    cost_class: 2.0
    cost_keypoints: 10.0
    cost_oks: 4.0
    focal_alpha: 0.25
  num_body_points: 17


DETRPosePostProcessor:
  num_select: 60
  num_body_points: 17


train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: PoseMosaic, output_size: 320}
        - {type: MixUpCopyPaste, mixup_prob: 0.5, copypaste_prob: 1.0}
        - {type: RandomZoomOut, p: 0.5}
        - {type: RandomHorizontalFlip}
        - {type: ColorJitter}
        - {type: Resize, size: [640, 640]}
        - {type: ToTensor}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]} 
      policy:
        name: stop_epoch
        epoch: [4, 36, 72]   # list 
        ops: ['PoseMosaic', 'MixUpCopyPaste', 'RandomZoomOut']
      mosaic_prob: 0.5

  collate_fn:
    type: BatchImageCollateFunction
    base_size: 640
    base_size_repeat: ~
    stop_epoch: 72 # epoch in [72, ~) stop `multiscales`

  shuffle: True
  total_batch_size: 32
  num_workers: 4

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ToTensor}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
  
  collate_fn:
    base_size: 640

  shuffle: False
  total_batch_size: 64
  num_workers: 4



use_amp: True
use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000
  start: 0

epoches: 72
clip_max_norm: 0.1


lr_scheduler:
  type: MultiStepLR
  milestones: [5000]
  gamma: 0.5

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 500


print_freq: 200
output_dir: './logs'
checkpoint_freq: 12

sync_bn: True
find_unused_parameters: False

use_amp: False
scaler:
  type: GradScaler
  enabled: False
