__include__: [
  '../dataset/coco_pose.yml',
  'ecpose.yml'
]


output_dir: outputs/ecpose_m

ViTAdapter:
  name: ecpose_vittplus
  embed_dim: 256
  weights_path: ecvits/ecpose_vittplus.pth
  interaction_indexes: [10, 11]  
  num_heads: 4

HybridEncoder:
  in_channels: [256, 256, 256]
  depth_mult: 0.67
  expansion: 0.75
  hidden_dim: 256
  dim_feedforward: 512

DETRTransformer:
  hidden_dim: 256
  dim_feedforward: 512
  num_decoder_layers: 4


eval_spatial_size: [640, 640] # h w

epoches: 92 

## Optimizer
optimizer:
  type: AdamW
  params: 
    -
      
      params: '^(?=.*.backbone)(?!.*(?:norm|bn|bias)).*$'  
      lr: 0.000025
    -
      params: '^(?=.*.backbone)(?=.*(?:norm|bn|bias)).*$'  
      lr: 0.000025
      weight_decay: 0.
    - 
      params: '^(?!.*\.backbone)(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.0001


train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: PoseMosaic, output_size: 320}
        - {type: MixUpCopyPaste, mixup_prob: 0.5}
        - {type: RandomZoomOut, p: 0.5}
        - {type: RandomHorizontalFlip}
        - {type: ColorJitter}
        - {type: Resize, size: [640, 640]}
        - {type: ToTensor}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]} 
      mosaic_prob: 0.5
      policy:
        epoch: [4, 45, 90]   # list 
       
  collate_fn:
    stop_epoch: 90
  

  
