# How often do you want to log the training stats.
logging_iter: 2
# Number of training epochs.
max_iter: 2
# Whether to benchmark speed or not.
speed_benchmark: True

# Number of epochs training single frame generator.
single_frame_epoch: 0
# How often to double the number of training frames in each clip.
num_epochs_temporal_step: 50

# Trainer options.
trainer:
    type: imaginaire.trainers.fs_vid2vid
    amp_config:
        enabled: True
    model_average_config:
        enabled: True
        beta: 0.999
        start_iteration: 500
        num_batch_norm_estimation_iterations: 0
    num_videos_to_test: 128
    num_frames_per_video: 10
    gan_mode: hinge
    gan_relativistic: False
    perceptual_loss:
        mode: 'vgg19'
        layers: ['relu_1_1', 'relu_2_1', 'relu_3_1', 'relu_4_1', 'relu_5_1']
        weights: [0.03125, 0.0625, 0.125, 0.25, 1.0]
        num_scales: 3
    loss_weight:
        gan: 1.0
        feature_matching: 10.0
        temporal_gan: 0.0
        perceptual: 10.0
        flow: 10.0
    init:
        type: xavier
        gain: 0.02
    distributed_data_parallel_params:
        find_unused_parameters: True

# Optimization option.
gen_opt:
    type: adam
    lr: 0.0001
    adam_beta1: 0.
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 100
        gamma: 0.5
dis_opt:
    type: adam
    lr: 0.0004
    adam_beta1: 0.
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 100
        gamma: 0.5


# Model options.
gen:
    type: imaginaire.generators.fs_vid2vid
    num_filters: 32
    max_num_filters: 1024
    num_downsamples: 5
    activation_norm_type: spatially_adaptive
    activation_norm_params:
        activation_norm_type: instance
        num_filters: 0
        kernel_size: 1
    weight_norm_type: spectral
    hyper:
        is_hyper_spade: True
        is_hyper_embed: True
        is_hyper_conv: False
        kernel_size: 3
        num_hyper_layers: 4
        num_fc_layers: 2
        activation_norm_type: instance
        weight_norm_type: spectral
        method_to_use_ref_labels: mul
        attention:
            num_filters: 32
            num_downsamples: 2
    flow:
        no_flow: False
        warp_ref: True
        generate_raw_output: False
        num_filters: 32
        max_num_filters: 1024
        num_downsamples: 3
        num_res_blocks: 6
        activation_norm_type: instance
        weight_norm_type: spectral
        flow_output_multiplier: 20
        multi_spade_combine:
            num_layers: 2
            embed:
                arch: unet
                num_filters: 32
                num_downsamples: 5
                kernel_size: 3
                sep_warp_embed: True
                weight_norm_type: spectral
        sep_prev_flow: False
    embed:
        use_embed: True
        arch: encoderdecoder
        num_filters: 32
        num_downsamples: 5
        kernel_size: 3
        weight_norm_type: spectral
dis:
    type: imaginaire.discriminators.fs_vid2vid
    image:
        num_filters: 64
        max_num_filters: 512
        num_discriminators: 2
        num_layers: 3
        weight_norm_type: spectral
        activation_norm_type: instance
flow_network:
    type: imaginaire.third_party.flow_net.flow_net

# Data options.
data:
    # Name of this dataset.
    name: 'face'
    # Which dataloader to use?
    type: imaginaire.datasets.paired_few_shot_videos
    num_frames_G: 2
    num_frames_D: 2
    initial_few_shot_K: 1
    for_face_dataset:
        add_upper_face: True
    # How many data loading workers per GPU?
    num_workers: 8
    input_types:
        - images:
            ext: jpg
            num_channels: 3
            normalize: True
        - landmarks-dlib68:
            ext: json
            num_channels: 1
            interpolator: None
            normalize: False
            pre_aug_ops: decode_json
            post_aug_ops: vis::imaginaire.utils.visualization.face::connect_face_keypoints

    # Apply these ops on the entire data, just before returning it.
    full_data_ops: imaginaire.model_utils.label::concat_labels,
                   imaginaire.model_utils.label::concat_few_shot_labels,
                   imaginaire.model_utils.fs_vid2vid::crop_face_from_data
    output_h_w: 256, 256
    input_labels:
        - landmarks-dlib68
    input_few_shot_labels:
        - few_shot_landmarks-dlib68

    # List which data types are keypoint.
    keypoint_data_types:
        - landmarks-dlib68

    # Which lmdb contains the ground truth image.
    input_image:
        - images

    # Which labels to be concatenated as final output label from dataloader.


    # Train dataset details.
    train:
        # Input LMDBs.
        roots:
            - dataset/unit_test/raw/fs_vid2vid/face
        # Batch size per GPU.
        batch_size: 1
        initial_sequence_length: 4
        # Data augmentations to be performed in given order.
        augmentations:
            resize_smallest_side: 512
            horizontal_flip: False



    # Validation dataset details.
    val:
        # Input LMDBs.
        roots:
            - dataset/unit_test/raw/fs_vid2vid/face
        # Batch size per GPU.
        batch_size: 1
        # If resize_h_w is not given, then it is assumed to be same as crop_h_w.
        augmentations:
            resize_smallest_side: 512
            horizontal_flip: False
