# How often do you want to log the training stats.
logging_iter: 2
# Number of training epochs.
max_iter: 2
speed_benchmark: True
trainer:
    type: imaginaire.trainers.spade
    gan_mode: hinge
    gan_relativistic: False
    perceptual_loss:
        mode: 'vgg19'
        layers: ['relu_1_1', 'relu_2_1', 'relu_3_1', 'relu_4_1', 'relu_5_1']
        weights: [0.03125, 0.0625, 0.125, 0.25, 1.0]
    loss_weight:
        gan: 1.0
        perceptual: 10.0
        feature_matching: 10.0
        kl: 0.05
    init:
        type: xavier
        gain: 0.02
gen_opt:
    type: adam
    lr: 0.0001
    adam_beta1: 0.
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 400
        gamma: 0.1
dis_opt:
    type: adam
    lr: 0.0004
    adam_beta1: 0.
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 400
        gamma: 0.1
gen:
    type: imaginaire.generators.spade
    version: v20
    style_dims: 256
    num_filters: 64
    kernel_size: 3
    weight_norm_type: 'spectral'
    global_adaptive_norm_type: 'instance'
    activation_norm_params:
        num_filters: 64
        kernel_size: 5
        separate_projection: False
        weight_norm_type: 'none'
        activation_norm_type: 'instance'
    style_enc:
        num_filters: 32
        kernel_size: 3
dis:
    type: imaginaire.discriminators.spade
    kernel_size: 3
    num_filters: 64
    max_num_filters: 512
    num_discriminators: 2
    num_layers: 5
    activation_norm_type: 'none'
    weight_norm_type: 'spectral'

# Data options.
data:
    # Which dataloader to use?
    type: imaginaire.datasets.paired_images
    # How many data loading workers per GPU?
    num_workers: 8
    input_types:
        - images:
            ext: jpg
            num_channels: 3
            normalize: True
            use_dont_care: False
        - seg_maps:
            ext: png
            num_channels: 1
            is_mask: True
            normalize: False
        - edge_maps:
            ext: png
            num_channels: 1
            normalize: False

    full_data_ops: imaginaire.model_utils.label::make_one_hot, imaginaire.model_utils.label::concat_labels
    use_dont_care: True
    one_hot_num_classes:
        seg_maps: 183
    input_labels:
        - seg_maps
        - edge_maps

    # Which lmdb contains the ground truth image.
    input_image:
        - images

    # Train dataset details.
    train:
        # Input LMDBs.
        roots:
            - dataset/unit_test/raw/spade
        # Batch size per GPU.
        batch_size: 1
        # Data augmentations to be performed in given order.
        augmentations:
            resize_smallest_side: 256
            # Rotate in (-rotate, rotate) in degrees.
            rotate: 0
            # Scale image by factor \in [1, 1+random_scale_limit].
            random_scale_limit: 0.2
            # Horizontal flip?
            horizontal_flip: True
            # Crop size.
            random_crop_h_w: 256, 256

    # Validation dataset details.
    val:
        # Input LMDBs.
        roots:
            - dataset/unit_test/raw/spade
        # Batch size per GPU.
        batch_size: 1
        # If resize_h_w is not given, then it is assumed to be same as crop_h_w.
        augmentations:
            resize_smallest_side: 256
            horizontal_flip: False