#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""This module implements GoogleNet models."""

from __future__ import annotations

__all__ = [
    "GoogleNet",
]

from typing import Any

import torch

from mon.coreml import model as mmodel
from mon.foundation import pathlib
from mon.globals import MODELS
from mon.vision.classify import base

_current_dir = pathlib.Path(__file__).absolute().parent


# region Model

@MODELS.register(name="googlenet")
class GoogleNet(base.ImageClassificationModel):
    """GoogleNet.
    
    See Also: :class:`mon.vision.enhance.base.ImageEnhancementModel`
    """
    
    configs     = {}
    zoo         = {
        "imagenet": {
            "name"       : "imagenet",
            "path"       : "https://download.pytorch.org/models/googlenet-1378be20.pth",
            "file_name"  : "googlenet-imagenet.pth",
            "num_classes": 1000,
        },
    }
    map_weights = {
        "backbone": {
            "0.bn.bias"                          : "conv1.bn.bias",
            "0.bn.num_batches_tracked"           : "conv1.bn.num_batches_tracked",
            "0.bn.running_mean"                  : "conv1.bn.running_mean",
            "0.bn.running_var"                   : "conv1.bn.running_var",
            "0.bn.weight"                        : "conv1.bn.weight",
            "0.conv.weight"                      : "conv1.conv.weight",
            "2.bn.bias"                          : "conv2.bn.bias",
            "2.bn.num_batches_tracked"           : "conv2.bn.num_batches_tracked",
            "2.bn.running_mean"                  : "conv2.bn.running_mean",
            "2.bn.running_var"                   : "conv2.bn.running_var",
            "2.bn.weight"                        : "conv2.bn.weight",
            "2.conv.weight"                      : "conv2.conv.weight",
            "3.bn.bias"                          : "conv3.bn.bias",
            "3.bn.num_batches_tracked"           : "conv3.bn.num_batches_tracked",
            "3.bn.running_mean"                  : "conv3.bn.running_mean",
            "3.bn.running_var"                   : "conv3.bn.running_var",
            "3.bn.weight"                        : "conv3.bn.weight",
            "3.conv.weight"                      : "conv3.conv.weight",
            "5.branch1.bn.bias"                  : "inception3a.branch1.bn.bias",
            "5.branch1.bn.num_batches_tracked"   : "inception3a.branch1.bn.num_batches_tracked",
            "5.branch1.bn.running_mean"          : "inception3a.branch1.bn.running_mean",
            "5.branch1.bn.running_var"           : "inception3a.branch1.bn.running_var",
            "5.branch1.bn.weight"                : "inception3a.branch1.bn.weight",
            "5.branch1.conv.weight"              : "inception3a.branch1.conv.weight",
            "5.branch2.0.bn.bias"                : "inception3a.branch2.0.bn.bias",
            "5.branch2.0.bn.num_batches_tracked" : "inception3a.branch2.0.bn.num_batches_tracked",
            "5.branch2.0.bn.running_mean"        : "inception3a.branch2.0.bn.running_mean",
            "5.branch2.0.bn.running_var"         : "inception3a.branch2.0.bn.running_var",
            "5.branch2.0.bn.weight"              : "inception3a.branch2.0.bn.weight",
            "5.branch2.0.conv.weight"            : "inception3a.branch2.0.conv.weight",
            "5.branch2.1.bn.bias"                : "inception3a.branch2.1.bn.bias",
            "5.branch2.1.bn.num_batches_tracked" : "inception3a.branch2.1.bn.num_batches_tracked",
            "5.branch2.1.bn.running_mean"        : "inception3a.branch2.1.bn.running_mean",
            "5.branch2.1.bn.running_var"         : "inception3a.branch2.1.bn.running_var",
            "5.branch2.1.bn.weight"              : "inception3a.branch2.1.bn.weight",
            "5.branch2.1.conv.weight"            : "inception3a.branch2.1.conv.weight",
            "5.branch3.0.bn.bias"                : "inception3a.branch3.0.bn.bias",
            "5.branch3.0.bn.num_batches_tracked" : "inception3a.branch3.0.bn.num_batches_tracked",
            "5.branch3.0.bn.running_mean"        : "inception3a.branch3.0.bn.running_mean",
            "5.branch3.0.bn.running_var"         : "inception3a.branch3.0.bn.running_var",
            "5.branch3.0.bn.weight"              : "inception3a.branch3.0.bn.weight",
            "5.branch3.0.conv.weight"            : "inception3a.branch3.0.conv.weight",
            "5.branch3.1.bn.bias"                : "inception3a.branch3.1.bn.bias",
            "5.branch3.1.bn.num_batches_tracked" : "inception3a.branch3.1.bn.num_batches_tracked",
            "5.branch3.1.bn.running_mean"        : "inception3a.branch3.1.bn.running_mean",
            "5.branch3.1.bn.running_var"         : "inception3a.branch3.1.bn.running_var",
            "5.branch3.1.bn.weight"              : "inception3a.branch3.1.bn.weight",
            "5.branch3.1.conv.weight"            : "inception3a.branch3.1.conv.weight",
            "5.branch4.1.bn.bias"                : "inception3a.branch4.1.bn.bias",
            "5.branch4.1.bn.num_batches_tracked" : "inception3a.branch4.1.bn.num_batches_tracked",
            "5.branch4.1.bn.running_mean"        : "inception3a.branch4.1.bn.running_mean",
            "5.branch4.1.bn.running_var"         : "inception3a.branch4.1.bn.running_var",
            "5.branch4.1.bn.weight"              : "inception3a.branch4.1.bn.weight",
            "5.branch4.1.conv.weight"            : "inception3a.branch4.1.conv.weight",
            "6.branch1.bn.bias"                  : "inception3b.branch1.bn.bias",
            "6.branch1.bn.num_batches_tracked"   : "inception3b.branch1.bn.num_batches_tracked",
            "6.branch1.bn.running_mean"          : "inception3b.branch1.bn.running_mean",
            "6.branch1.bn.running_var"           : "inception3b.branch1.bn.running_var",
            "6.branch1.bn.weight"                : "inception3b.branch1.bn.weight",
            "6.branch1.conv.weight"              : "inception3b.branch1.conv.weight",
            "6.branch2.0.bn.bias"                : "inception3b.branch2.0.bn.bias",
            "6.branch2.0.bn.num_batches_tracked" : "inception3b.branch2.0.bn.num_batches_tracked",
            "6.branch2.0.bn.running_mean"        : "inception3b.branch2.0.bn.running_mean",
            "6.branch2.0.bn.running_var"         : "inception3b.branch2.0.bn.running_var",
            "6.branch2.0.bn.weight"              : "inception3b.branch2.0.bn.weight",
            "6.branch2.0.conv.weight"            : "inception3b.branch2.0.conv.weight",
            "6.branch2.1.bn.bias"                : "inception3b.branch2.1.bn.bias",
            "6.branch2.1.bn.num_batches_tracked" : "inception3b.branch2.1.bn.num_batches_tracked",
            "6.branch2.1.bn.running_mean"        : "inception3b.branch2.1.bn.running_mean",
            "6.branch2.1.bn.running_var"         : "inception3b.branch2.1.bn.running_var",
            "6.branch2.1.bn.weight"              : "inception3b.branch2.1.bn.weight",
            "6.branch2.1.conv.weight"            : "inception3b.branch2.1.conv.weight",
            "6.branch3.0.bn.bias"                : "inception3b.branch3.0.bn.bias",
            "6.branch3.0.bn.num_batches_tracked" : "inception3b.branch3.0.bn.num_batches_tracked",
            "6.branch3.0.bn.running_mean"        : "inception3b.branch3.0.bn.running_mean",
            "6.branch3.0.bn.running_var"         : "inception3b.branch3.0.bn.running_var",
            "6.branch3.0.bn.weight"              : "inception3b.branch3.0.bn.weight",
            "6.branch3.0.conv.weight"            : "inception3b.branch3.0.conv.weight",
            "6.branch3.1.bn.bias"                : "inception3b.branch3.1.bn.bias",
            "6.branch3.1.bn.num_batches_tracked" : "inception3b.branch3.1.bn.num_batches_tracked",
            "6.branch3.1.bn.running_mean"        : "inception3b.branch3.1.bn.running_mean",
            "6.branch3.1.bn.running_var"         : "inception3b.branch3.1.bn.running_var",
            "6.branch3.1.bn.weight"              : "inception3b.branch3.1.bn.weight",
            "6.branch3.1.conv.weight"            : "inception3b.branch3.1.conv.weight",
            "6.branch4.1.bn.bias"                : "inception3b.branch4.1.bn.bias",
            "6.branch4.1.bn.num_batches_tracked" : "inception3b.branch4.1.bn.num_batches_tracked",
            "6.branch4.1.bn.running_mean"        : "inception3b.branch4.1.bn.running_mean",
            "6.branch4.1.bn.running_var"         : "inception3b.branch4.1.bn.running_var",
            "6.branch4.1.bn.weight"              : "inception3b.branch4.1.bn.weight",
            "6.branch4.1.conv.weight"            : "inception3b.branch4.1.conv.weight",
            "8.branch1.bn.bias"                  : "inception4a.branch1.bn.bias",
            "8.branch1.bn.num_batches_tracked"   : "inception4a.branch1.bn.num_batches_tracked",
            "8.branch1.bn.running_mean"          : "inception4a.branch1.bn.running_mean",
            "8.branch1.bn.running_var"           : "inception4a.branch1.bn.running_var",
            "8.branch1.bn.weight"                : "inception4a.branch1.bn.weight",
            "8.branch1.conv.weight"              : "inception4a.branch1.conv.weight",
            "8.branch2.0.bn.bias"                : "inception4a.branch2.0.bn.bias",
            "8.branch2.0.bn.num_batches_tracked" : "inception4a.branch2.0.bn.num_batches_tracked",
            "8.branch2.0.bn.running_mean"        : "inception4a.branch2.0.bn.running_mean",
            "8.branch2.0.bn.running_var"         : "inception4a.branch2.0.bn.running_var",
            "8.branch2.0.bn.weight"              : "inception4a.branch2.0.bn.weight",
            "8.branch2.0.conv.weight"            : "inception4a.branch2.0.conv.weight",
            "8.branch2.1.bn.bias"                : "inception4a.branch2.1.bn.bias",
            "8.branch2.1.bn.num_batches_tracked" : "inception4a.branch2.1.bn.num_batches_tracked",
            "8.branch2.1.bn.running_mean"        : "inception4a.branch2.1.bn.running_mean",
            "8.branch2.1.bn.running_var"         : "inception4a.branch2.1.bn.running_var",
            "8.branch2.1.bn.weight"              : "inception4a.branch2.1.bn.weight",
            "8.branch2.1.conv.weight"            : "inception4a.branch2.1.conv.weight",
            "8.branch3.0.bn.bias"                : "inception4a.branch3.0.bn.bias",
            "8.branch3.0.bn.num_batches_tracked" : "inception4a.branch3.0.bn.num_batches_tracked",
            "8.branch3.0.bn.running_mean"        : "inception4a.branch3.0.bn.running_mean",
            "8.branch3.0.bn.running_var"         : "inception4a.branch3.0.bn.running_var",
            "8.branch3.0.bn.weight"              : "inception4a.branch3.0.bn.weight",
            "8.branch3.0.conv.weight"            : "inception4a.branch3.0.conv.weight",
            "8.branch3.1.bn.bias"                : "inception4a.branch3.1.bn.bias",
            "8.branch3.1.bn.num_batches_tracked" : "inception4a.branch3.1.bn.num_batches_tracked",
            "8.branch3.1.bn.running_mean"        : "inception4a.branch3.1.bn.running_mean",
            "8.branch3.1.bn.running_var"         : "inception4a.branch3.1.bn.running_var",
            "8.branch3.1.bn.weight"              : "inception4a.branch3.1.bn.weight",
            "8.branch3.1.conv.weight"            : "inception4a.branch3.1.conv.weight",
            "8.branch4.1.bn.bias"                : "inception4a.branch4.1.bn.bias",
            "8.branch4.1.bn.num_batches_tracked" : "inception4a.branch4.1.bn.num_batches_tracked",
            "8.branch4.1.bn.running_mean"        : "inception4a.branch4.1.bn.running_mean",
            "8.branch4.1.bn.running_var"         : "inception4a.branch4.1.bn.running_var",
            "8.branch4.1.bn.weight"              : "inception4a.branch4.1.bn.weight",
            "8.branch4.1.conv.weight"            : "inception4a.branch4.1.conv.weight",
            "9.branch1.bn.bias"                  : "inception4b.branch1.bn.bias",
            "9.branch1.bn.num_batches_tracked"   : "inception4b.branch1.bn.num_batches_tracked",
            "9.branch1.bn.running_mean"          : "inception4b.branch1.bn.running_mean",
            "9.branch1.bn.running_var"           : "inception4b.branch1.bn.running_var",
            "9.branch1.bn.weight"                : "inception4b.branch1.bn.weight",
            "9.branch1.conv.weight"              : "inception4b.branch1.conv.weight",
            "9.branch2.0.bn.bias"                : "inception4b.branch2.0.bn.bias",
            "9.branch2.0.bn.num_batches_tracked" : "inception4b.branch2.0.bn.num_batches_tracked",
            "9.branch2.0.bn.running_mean"        : "inception4b.branch2.0.bn.running_mean",
            "9.branch2.0.bn.running_var"         : "inception4b.branch2.0.bn.running_var",
            "9.branch2.0.bn.weight"              : "inception4b.branch2.0.bn.weight",
            "9.branch2.0.conv.weight"            : "inception4b.branch2.0.conv.weight",
            "9.branch2.1.bn.bias"                : "inception4b.branch2.1.bn.bias",
            "9.branch2.1.bn.num_batches_tracked" : "inception4b.branch2.1.bn.num_batches_tracked",
            "9.branch2.1.bn.running_mean"        : "inception4b.branch2.1.bn.running_mean",
            "9.branch2.1.bn.running_var"         : "inception4b.branch2.1.bn.running_var",
            "9.branch2.1.bn.weight"              : "inception4b.branch2.1.bn.weight",
            "9.branch2.1.conv.weight"            : "inception4b.branch2.1.conv.weight",
            "9.branch3.0.bn.bias"                : "inception4b.branch3.0.bn.bias",
            "9.branch3.0.bn.num_batches_tracked" : "inception4b.branch3.0.bn.num_batches_tracked",
            "9.branch3.0.bn.running_mean"        : "inception4b.branch3.0.bn.running_mean",
            "9.branch3.0.bn.running_var"         : "inception4b.branch3.0.bn.running_var",
            "9.branch3.0.bn.weight"              : "inception4b.branch3.0.bn.weight",
            "9.branch3.0.conv.weight"            : "inception4b.branch3.0.conv.weight",
            "9.branch3.1.bn.bias"                : "inception4b.branch3.1.bn.bias",
            "9.branch3.1.bn.num_batches_tracked" : "inception4b.branch3.1.bn.num_batches_tracked",
            "9.branch3.1.bn.running_mean"        : "inception4b.branch3.1.bn.running_mean",
            "9.branch3.1.bn.running_var"         : "inception4b.branch3.1.bn.running_var",
            "9.branch3.1.bn.weight"              : "inception4b.branch3.1.bn.weight",
            "9.branch3.1.conv.weight"            : "inception4b.branch3.1.conv.weight",
            "9.branch4.1.bn.bias"                : "inception4b.branch4.1.bn.bias",
            "9.branch4.1.bn.num_batches_tracked" : "inception4b.branch4.1.bn.num_batches_tracked",
            "9.branch4.1.bn.running_mean"        : "inception4b.branch4.1.bn.running_mean",
            "9.branch4.1.bn.running_var"         : "inception4b.branch4.1.bn.running_var",
            "9.branch4.1.bn.weight"              : "inception4b.branch4.1.bn.weight",
            "9.branch4.1.conv.weight"            : "inception4b.branch4.1.conv.weight",
            "10.branch1.bn.bias"                 : "inception4c.branch1.bn.bias",
            "10.branch1.bn.num_batches_tracked"  : "inception4c.branch1.bn.num_batches_tracked",
            "10.branch1.bn.running_mean"         : "inception4c.branch1.bn.running_mean",
            "10.branch1.bn.running_var"          : "inception4c.branch1.bn.running_var",
            "10.branch1.bn.weight"               : "inception4c.branch1.bn.weight",
            "10.branch1.conv.weight"             : "inception4c.branch1.conv.weight",
            "10.branch2.0.bn.bias"               : "inception4c.branch2.0.bn.bias",
            "10.branch2.0.bn.num_batches_tracked": "inception4c.branch2.0.bn.num_batches_tracked",
            "10.branch2.0.bn.running_mean"       : "inception4c.branch2.0.bn.running_mean",
            "10.branch2.0.bn.running_var"        : "inception4c.branch2.0.bn.running_var",
            "10.branch2.0.bn.weight"             : "inception4c.branch2.0.bn.weight",
            "10.branch2.0.conv.weight"           : "inception4c.branch2.0.conv.weight",
            "10.branch2.1.bn.bias"               : "inception4c.branch2.1.bn.bias",
            "10.branch2.1.bn.num_batches_tracked": "inception4c.branch2.1.bn.num_batches_tracked",
            "10.branch2.1.bn.running_mean"       : "inception4c.branch2.1.bn.running_mean",
            "10.branch2.1.bn.running_var"        : "inception4c.branch2.1.bn.running_var",
            "10.branch2.1.bn.weight"             : "inception4c.branch2.1.bn.weight",
            "10.branch2.1.conv.weight"           : "inception4c.branch2.1.conv.weight",
            "10.branch3.0.bn.bias"               : "inception4c.branch3.0.bn.bias",
            "10.branch3.0.bn.num_batches_tracked": "inception4c.branch3.0.bn.num_batches_tracked",
            "10.branch3.0.bn.running_mean"       : "inception4c.branch3.0.bn.running_mean",
            "10.branch3.0.bn.running_var"        : "inception4c.branch3.0.bn.running_var",
            "10.branch3.0.bn.weight"             : "inception4c.branch3.0.bn.weight",
            "10.branch3.0.conv.weight"           : "inception4c.branch3.0.conv.weight",
            "10.branch3.1.bn.bias"               : "inception4c.branch3.1.bn.bias",
            "10.branch3.1.bn.num_batches_tracked": "inception4c.branch3.1.bn.num_batches_tracked",
            "10.branch3.1.bn.running_mean"       : "inception4c.branch3.1.bn.running_mean",
            "10.branch3.1.bn.running_var"        : "inception4c.branch3.1.bn.running_var",
            "10.branch3.1.bn.weight"             : "inception4c.branch3.1.bn.weight",
            "10.branch3.1.conv.weight"           : "inception4c.branch3.1.conv.weight",
            "10.branch4.1.bn.bias"               : "inception4c.branch4.1.bn.bias",
            "10.branch4.1.bn.num_batches_tracked": "inception4c.branch4.1.bn.num_batches_tracked",
            "10.branch4.1.bn.running_mean"       : "inception4c.branch4.1.bn.running_mean",
            "10.branch4.1.bn.running_var"        : "inception4c.branch4.1.bn.running_var",
            "10.branch4.1.bn.weight"             : "inception4c.branch4.1.bn.weight",
            "10.branch4.1.conv.weight"           : "inception4c.branch4.1.conv.weight",
            "11.branch1.bn.bias"                 : "inception4d.branch1.bn.bias",
            "11.branch1.bn.num_batches_tracked"  : "inception4d.branch1.bn.num_batches_tracked",
            "11.branch1.bn.running_mean"         : "inception4d.branch1.bn.running_mean",
            "11.branch1.bn.running_var"          : "inception4d.branch1.bn.running_var",
            "11.branch1.bn.weight"               : "inception4d.branch1.bn.weight",
            "11.branch1.conv.weight"             : "inception4d.branch1.conv.weight",
            "11.branch2.0.bn.bias"               : "inception4d.branch2.0.bn.bias",
            "11.branch2.0.bn.num_batches_tracked": "inception4d.branch2.0.bn.num_batches_tracked",
            "11.branch2.0.bn.running_mean"       : "inception4d.branch2.0.bn.running_mean",
            "11.branch2.0.bn.running_var"        : "inception4d.branch2.0.bn.running_var",
            "11.branch2.0.bn.weight"             : "inception4d.branch2.0.bn.weight",
            "11.branch2.0.conv.weight"           : "inception4d.branch2.0.conv.weight",
            "11.branch2.1.bn.bias"               : "inception4d.branch2.1.bn.bias",
            "11.branch2.1.bn.num_batches_tracked": "inception4d.branch2.1.bn.num_batches_tracked",
            "11.branch2.1.bn.running_mean"       : "inception4d.branch2.1.bn.running_mean",
            "11.branch2.1.bn.running_var"        : "inception4d.branch2.1.bn.running_var",
            "11.branch2.1.bn.weight"             : "inception4d.branch2.1.bn.weight",
            "11.branch2.1.conv.weight"           : "inception4d.branch2.1.conv.weight",
            "11.branch3.0.bn.bias"               : "inception4d.branch3.0.bn.bias",
            "11.branch3.0.bn.num_batches_tracked": "inception4d.branch3.0.bn.num_batches_tracked",
            "11.branch3.0.bn.running_mean"       : "inception4d.branch3.0.bn.running_mean",
            "11.branch3.0.bn.running_var"        : "inception4d.branch3.0.bn.running_var",
            "11.branch3.0.bn.weight"             : "inception4d.branch3.0.bn.weight",
            "11.branch3.0.conv.weight"           : "inception4d.branch3.0.conv.weight",
            "11.branch3.1.bn.bias"               : "inception4d.branch3.1.bn.bias",
            "11.branch3.1.bn.num_batches_tracked": "inception4d.branch3.1.bn.num_batches_tracked",
            "11.branch3.1.bn.running_mean"       : "inception4d.branch3.1.bn.running_mean",
            "11.branch3.1.bn.running_var"        : "inception4d.branch3.1.bn.running_var",
            "11.branch3.1.bn.weight"             : "inception4d.branch3.1.bn.weight",
            "11.branch3.1.conv.weight"           : "inception4d.branch3.1.conv.weight",
            "11.branch4.1.bn.bias"               : "inception4d.branch4.1.bn.bias",
            "11.branch4.1.bn.num_batches_tracked": "inception4d.branch4.1.bn.num_batches_tracked",
            "11.branch4.1.bn.running_mean"       : "inception4d.branch4.1.bn.running_mean",
            "11.branch4.1.bn.running_var"        : "inception4d.branch4.1.bn.running_var",
            "11.branch4.1.bn.weight"             : "inception4d.branch4.1.bn.weight",
            "11.branch4.1.conv.weight"           : "inception4d.branch4.1.conv.weight",
            "12.branch1.bn.bias"                 : "inception4e.branch1.bn.bias",
            "12.branch1.bn.num_batches_tracked"  : "inception4e.branch1.bn.num_batches_tracked",
            "12.branch1.bn.running_mean"         : "inception4e.branch1.bn.running_mean",
            "12.branch1.bn.running_var"          : "inception4e.branch1.bn.running_var",
            "12.branch1.bn.weight"               : "inception4e.branch1.bn.weight",
            "12.branch1.conv.weight"             : "inception4e.branch1.conv.weight",
            "12.branch2.0.bn.bias"               : "inception4e.branch2.0.bn.bias",
            "12.branch2.0.bn.num_batches_tracked": "inception4e.branch2.0.bn.num_batches_tracked",
            "12.branch2.0.bn.running_mean"       : "inception4e.branch2.0.bn.running_mean",
            "12.branch2.0.bn.running_var"        : "inception4e.branch2.0.bn.running_var",
            "12.branch2.0.bn.weight"             : "inception4e.branch2.0.bn.weight",
            "12.branch2.0.conv.weight"           : "inception4e.branch2.0.conv.weight",
            "12.branch2.1.bn.bias"               : "inception4e.branch2.1.bn.bias",
            "12.branch2.1.bn.num_batches_tracked": "inception4e.branch2.1.bn.num_batches_tracked",
            "12.branch2.1.bn.running_mean"       : "inception4e.branch2.1.bn.running_mean",
            "12.branch2.1.bn.running_var"        : "inception4e.branch2.1.bn.running_var",
            "12.branch2.1.bn.weight"             : "inception4e.branch2.1.bn.weight",
            "12.branch2.1.conv.weight"           : "inception4e.branch2.1.conv.weight",
            "12.branch3.0.bn.bias"               : "inception4e.branch3.0.bn.bias",
            "12.branch3.0.bn.num_batches_tracked": "inception4e.branch3.0.bn.num_batches_tracked",
            "12.branch3.0.bn.running_mean"       : "inception4e.branch3.0.bn.running_mean",
            "12.branch3.0.bn.running_var"        : "inception4e.branch3.0.bn.running_var",
            "12.branch3.0.bn.weight"             : "inception4e.branch3.0.bn.weight",
            "12.branch3.0.conv.weight"           : "inception4e.branch3.0.conv.weight",
            "12.branch3.1.bn.bias"               : "inception4e.branch3.1.bn.bias",
            "12.branch3.1.bn.num_batches_tracked": "inception4e.branch3.1.bn.num_batches_tracked",
            "12.branch3.1.bn.running_mean"       : "inception4e.branch3.1.bn.running_mean",
            "12.branch3.1.bn.running_var"        : "inception4e.branch3.1.bn.running_var",
            "12.branch3.1.bn.weight"             : "inception4e.branch3.1.bn.weight",
            "12.branch3.1.conv.weight"           : "inception4e.branch3.1.conv.weight",
            "12.branch4.1.bn.bias"               : "inception4e.branch4.1.bn.bias",
            "12.branch4.1.bn.num_batches_tracked": "inception4e.branch4.1.bn.num_batches_tracked",
            "12.branch4.1.bn.running_mean"       : "inception4e.branch4.1.bn.running_mean",
            "12.branch4.1.bn.running_var"        : "inception4e.branch4.1.bn.running_var",
            "12.branch4.1.bn.weight"             : "inception4e.branch4.1.bn.weight",
            "12.branch4.1.conv.weight"           : "inception4e.branch4.1.conv.weight",
            "14.branch1.bn.bias"                 : "inception5a.branch1.bn.bias",
            "14.branch1.bn.num_batches_tracked"  : "inception5a.branch1.bn.num_batches_tracked",
            "14.branch1.bn.running_mean"         : "inception5a.branch1.bn.running_mean",
            "14.branch1.bn.running_var"          : "inception5a.branch1.bn.running_var",
            "14.branch1.bn.weight"               : "inception5a.branch1.bn.weight",
            "14.branch1.conv.weight"             : "inception5a.branch1.conv.weight",
            "14.branch2.0.bn.bias"               : "inception5a.branch2.0.bn.bias",
            "14.branch2.0.bn.num_batches_tracked": "inception5a.branch2.0.bn.num_batches_tracked",
            "14.branch2.0.bn.running_mean"       : "inception5a.branch2.0.bn.running_mean",
            "14.branch2.0.bn.running_var"        : "inception5a.branch2.0.bn.running_var",
            "14.branch2.0.bn.weight"             : "inception5a.branch2.0.bn.weight",
            "14.branch2.0.conv.weight"           : "inception5a.branch2.0.conv.weight",
            "14.branch2.1.bn.bias"               : "inception5a.branch2.1.bn.bias",
            "14.branch2.1.bn.num_batches_tracked": "inception5a.branch2.1.bn.num_batches_tracked",
            "14.branch2.1.bn.running_mean"       : "inception5a.branch2.1.bn.running_mean",
            "14.branch2.1.bn.running_var"        : "inception5a.branch2.1.bn.running_var",
            "14.branch2.1.bn.weight"             : "inception5a.branch2.1.bn.weight",
            "14.branch2.1.conv.weight"           : "inception5a.branch2.1.conv.weight",
            "14.branch3.0.bn.bias"               : "inception5a.branch3.0.bn.bias",
            "14.branch3.0.bn.num_batches_tracked": "inception5a.branch3.0.bn.num_batches_tracked",
            "14.branch3.0.bn.running_mean"       : "inception5a.branch3.0.bn.running_mean",
            "14.branch3.0.bn.running_var"        : "inception5a.branch3.0.bn.running_var",
            "14.branch3.0.bn.weight"             : "inception5a.branch3.0.bn.weight",
            "14.branch3.0.conv.weight"           : "inception5a.branch3.0.conv.weight",
            "14.branch3.1.bn.bias"               : "inception5a.branch3.1.bn.bias",
            "14.branch3.1.bn.num_batches_tracked": "inception5a.branch3.1.bn.num_batches_tracked",
            "14.branch3.1.bn.running_mean"       : "inception5a.branch3.1.bn.running_mean",
            "14.branch3.1.bn.running_var"        : "inception5a.branch3.1.bn.running_var",
            "14.branch3.1.bn.weight"             : "inception5a.branch3.1.bn.weight",
            "14.branch3.1.conv.weight"           : "inception5a.branch3.1.conv.weight",
            "14.branch4.1.bn.bias"               : "inception5a.branch4.1.bn.bias",
            "14.branch4.1.bn.num_batches_tracked": "inception5a.branch4.1.bn.num_batches_tracked",
            "14.branch4.1.bn.running_mean"       : "inception5a.branch4.1.bn.running_mean",
            "14.branch4.1.bn.running_var"        : "inception5a.branch4.1.bn.running_var",
            "14.branch4.1.bn.weight"             : "inception5a.branch4.1.bn.weight",
            "14.branch4.1.conv.weight"           : "inception5a.branch4.1.conv.weight",
            "15.branch1.bn.bias"                 : "inception5b.branch1.bn.bias",
            "15.branch1.bn.num_batches_tracked"  : "inception5b.branch1.bn.num_batches_tracked",
            "15.branch1.bn.running_mean"         : "inception5b.branch1.bn.running_mean",
            "15.branch1.bn.running_var"          : "inception5b.branch1.bn.running_var",
            "15.branch1.bn.weight"               : "inception5b.branch1.bn.weight",
            "15.branch1.conv.weight"             : "inception5b.branch1.conv.weight",
            "15.branch2.0.bn.bias"               : "inception5b.branch2.0.bn.bias",
            "15.branch2.0.bn.num_batches_tracked": "inception5b.branch2.0.bn.num_batches_tracked",
            "15.branch2.0.bn.running_mean"       : "inception5b.branch2.0.bn.running_mean",
            "15.branch2.0.bn.running_var"        : "inception5b.branch2.0.bn.running_var",
            "15.branch2.0.bn.weight"             : "inception5b.branch2.0.bn.weight",
            "15.branch2.0.conv.weight"           : "inception5b.branch2.0.conv.weight",
            "15.branch2.1.bn.bias"               : "inception5b.branch2.1.bn.bias",
            "15.branch2.1.bn.num_batches_tracked": "inception5b.branch2.1.bn.num_batches_tracked",
            "15.branch2.1.bn.running_mean"       : "inception5b.branch2.1.bn.running_mean",
            "15.branch2.1.bn.running_var"        : "inception5b.branch2.1.bn.running_var",
            "15.branch2.1.bn.weight"             : "inception5b.branch2.1.bn.weight",
            "15.branch2.1.conv.weight"           : "inception5b.branch2.1.conv.weight",
            "15.branch3.0.bn.bias"               : "inception5b.branch3.0.bn.bias",
            "15.branch3.0.bn.num_batches_tracked": "inception5b.branch3.0.bn.num_batches_tracked",
            "15.branch3.0.bn.running_mean"       : "inception5b.branch3.0.bn.running_mean",
            "15.branch3.0.bn.running_var"        : "inception5b.branch3.0.bn.running_var",
            "15.branch3.0.bn.weight"             : "inception5b.branch3.0.bn.weight",
            "15.branch3.0.conv.weight"           : "inception5b.branch3.0.conv.weight",
            "15.branch3.1.bn.bias"               : "inception5b.branch3.1.bn.bias",
            "15.branch3.1.bn.num_batches_tracked": "inception5b.branch3.1.bn.num_batches_tracked",
            "15.branch3.1.bn.running_mean"       : "inception5b.branch3.1.bn.running_mean",
            "15.branch3.1.bn.running_var"        : "inception5b.branch3.1.bn.running_var",
            "15.branch3.1.bn.weight"             : "inception5b.branch3.1.bn.weight",
            "15.branch3.1.conv.weight"           : "inception5b.branch3.1.conv.weight",
            "15.branch4.1.bn.bias"               : "inception5b.branch4.1.bn.bias",
            "15.branch4.1.bn.num_batches_tracked": "inception5b.branch4.1.bn.num_batches_tracked",
            "15.branch4.1.bn.running_mean"       : "inception5b.branch4.1.bn.running_mean",
            "15.branch4.1.bn.running_var"        : "inception5b.branch4.1.bn.running_var",
            "15.branch4.1.bn.weight"             : "inception5b.branch4.1.bn.weight",
            "15.branch4.1.conv.weight"           : "inception5b.branch4.1.conv.weight",
            "16.conv.bn.bias"                    : "aux1.conv.bn.bias",
            "16.conv.bn.num_batches_tracked"     : "aux1.conv.bn.num_batches_tracked",
            "16.conv.bn.running_mean"            : "aux1.conv.bn.running_mean",
            "16.conv.bn.running_var"             : "aux1.conv.bn.running_var",
            "16.conv.bn.weight"                  : "aux1.conv.bn.weight",
            "16.conv.conv.weight"                : "aux1.conv.conv.weight",
            "16.fc1.bias"                        : "aux1.fc1.bias",
            "16.fc1.weight"                      : "aux1.fc1.weight",
            "16.fc2.bias"                        : "aux1.fc2.bias",
            "16.fc2.weight"                      : "aux1.fc2.weight",
            "17.conv.bn.bias"                    : "aux2.conv.bn.bias",
            "17.conv.bn.num_batches_tracked"     : "aux2.conv.bn.num_batches_tracked",
            "17.conv.bn.running_mean"            : "aux2.conv.bn.running_mean",
            "17.conv.bn.running_var"             : "aux2.conv.bn.running_var",
            "17.conv.bn.weight"                  : "aux2.conv.bn.weight",
            "17.conv.conv.weight"                : "aux2.conv.conv.weight",
            "17.fc1.bias"                        : "aux2.fc1.bias",
            "17.fc1.weight"                      : "aux2.fc1.weight",
            "17.fc2.bias"                        : "aux2.fc2.bias",
            "17.fc2.weight"                      : "aux2.fc2.weight",
        },
        "head"    : {
            "18.fc.bias"  : "fc.bias",
            "18.fc.weight": "fc.weight",
        },
    }

    def __init__(self, *args, **kwargs):
        if "config" in kwargs:
            _ = kwargs.pop("config")
        super().__init__(config="googlenet.yaml", *args, **kwargs)
    
    def init_weights(self, m: torch.nn.Module):
        classname    = m.__class__.__name__
        init_weights = self.config["init_weights"]
        if init_weights:
            if isinstance(m, torch.nn.Conv2d) or isinstance(m, torch.nn.Linear):
                stddev = float(m.stddev) if hasattr(m, "stddev") else 0.1  # type: ignore
                torch.nn.init.trunc_normal_(m.weight, mean=0.0, std=stddev, a=-2, b=2)
            elif isinstance(m, torch.nn.BatchNorm2d):
                torch.nn.init.constant_(m.weight, 1)
                torch.nn.init.constant_(m.bias, 0)
    
    def load_weights(self):
        """Load weights. It only loads the intersection layers of matching keys
        and shapes between the current model and weights.
        """
        if isinstance(self.weights, dict) \
            and self.weights["name"] in ["imagenet"]:
            state_dict = mmodel.load_state_dict_from_path(
                model_dir=self.zoo_dir, **self.weights
            )
            model_state_dict = self.model.state_dict()
            """
            for k in self.model.state_dict().keys():
                print(f"\"{k}\": ")
            for k in state_dict.keys():
                print(f"\"{k}\"")
            """
            for k, v in self.map_weights["backbone"].items():
                model_state_dict[k] = state_dict[v]
            if self.weights["num_classes"] == self.num_classes:
                for k, v in self.map_weights["head"].items():
                    model_state_dict[k] = state_dict[v]
            self.model.load_state_dict(model_state_dict)
        else:
            super().load_weights()
        
# endregion
