#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""This module implements Inception models."""

from __future__ import annotations

__all__ = [
    "Inception",
]

import torch

from mon.coreml import model as mmodel
from mon.foundation import pathlib
from mon.globals import MODELS
from mon.vision.classify import base

_current_dir = pathlib.Path(__file__).absolute().parent


# region Model

@MODELS.register(name="inception")
class Inception(base.ImageClassificationModel):
    """Inception.
    
    See Also: :class:`mon.vision.enhance.base.ImageEnhancementModel`
    """
    
    configs     = {}
    zoo         = {
        "imagenet": {
            "name"       : "imagenet",
            "path"       : "https://download.pytorch.org/models/inception_v3_google-0cc3c7bd.pth",
            "file_name"  : "inception3-imagenet.pth",
            "num_classes": 1000,
        },
    }
    map_weights = {
        "backbone": {
            "0.bn.bias"                         : "Conv2d_1a_3x3.bn.bias",
            "0.bn.running_mean"                 : "Conv2d_1a_3x3.bn.running_mean",
            "0.bn.running_var"                  : "Conv2d_1a_3x3.bn.running_var",
            "0.bn.weight"                       : "Conv2d_1a_3x3.bn.weight",
            "0.conv.weight"                     : "Conv2d_1a_3x3.conv.weight",
            "1.bn.bias"                         : "Conv2d_2a_3x3.bn.bias",
            "1.bn.running_mean"                 : "Conv2d_2a_3x3.bn.running_mean",
            "1.bn.running_var"                  : "Conv2d_2a_3x3.bn.running_var",
            "1.bn.weight"                       : "Conv2d_2a_3x3.bn.weight",
            "1.conv.weight"                     : "Conv2d_2a_3x3.conv.weight",
            "2.bn.bias"                         : "Conv2d_2b_3x3.bn.bias",
            "2.bn.running_mean"                 : "Conv2d_2b_3x3.bn.running_mean",
            "2.bn.running_var"                  : "Conv2d_2b_3x3.bn.running_var",
            "2.bn.weight"                       : "Conv2d_2b_3x3.bn.weight",
            "2.conv.weight"                     : "Conv2d_2b_3x3.conv.weight",
            "4.bn.bias"                         : "Conv2d_3b_1x1.bn.bias",
            "4.bn.running_mean"                 : "Conv2d_3b_1x1.bn.running_mean",
            "4.bn.running_var"                  : "Conv2d_3b_1x1.bn.running_var",
            "4.bn.weight"                       : "Conv2d_3b_1x1.bn.weight",
            "4.conv.weight"                     : "Conv2d_3b_1x1.conv.weight",
            "5.bn.bias"                         : "Conv2d_4a_3x3.bn.bias",
            "5.bn.running_mean"                 : "Conv2d_4a_3x3.bn.running_mean",
            "5.bn.running_var"                  : "Conv2d_4a_3x3.bn.running_var",
            "5.bn.weight"                       : "Conv2d_4a_3x3.bn.weight",
            "5.conv.weight"                     : "Conv2d_4a_3x3.conv.weight",
            "7.branch1x1.bn.bias"               : "Mixed_5b.branch1x1.bn.bias",
            "7.branch1x1.bn.running_mean"       : "Mixed_5b.branch1x1.bn.running_mean",
            "7.branch1x1.bn.running_var"        : "Mixed_5b.branch1x1.bn.running_var",
            "7.branch1x1.bn.weight"             : "Mixed_5b.branch1x1.bn.weight",
            "7.branch1x1.conv.weight"           : "Mixed_5b.branch1x1.conv.weight",
            "7.branch3x3dbl_1.bn.bias"          : "Mixed_5b.branch3x3dbl_1.bn.bias",
            "7.branch3x3dbl_1.bn.running_mean"  : "Mixed_5b.branch3x3dbl_1.bn.running_mean",
            "7.branch3x3dbl_1.bn.running_var"   : "Mixed_5b.branch3x3dbl_1.bn.running_var",
            "7.branch3x3dbl_1.bn.weight"        : "Mixed_5b.branch3x3dbl_1.bn.weight",
            "7.branch3x3dbl_1.conv.weight"      : "Mixed_5b.branch3x3dbl_1.conv.weight",
            "7.branch3x3dbl_2.bn.bias"          : "Mixed_5b.branch3x3dbl_2.bn.bias",
            "7.branch3x3dbl_2.bn.running_mean"  : "Mixed_5b.branch3x3dbl_2.bn.running_mean",
            "7.branch3x3dbl_2.bn.running_var"   : "Mixed_5b.branch3x3dbl_2.bn.running_var",
            "7.branch3x3dbl_2.bn.weight"        : "Mixed_5b.branch3x3dbl_2.bn.weight",
            "7.branch3x3dbl_2.conv.weight"      : "Mixed_5b.branch3x3dbl_2.conv.weight",
            "7.branch3x3dbl_3.bn.bias"          : "Mixed_5b.branch3x3dbl_3.bn.bias",
            "7.branch3x3dbl_3.bn.running_mean"  : "Mixed_5b.branch3x3dbl_3.bn.running_mean",
            "7.branch3x3dbl_3.bn.running_var"   : "Mixed_5b.branch3x3dbl_3.bn.running_var",
            "7.branch3x3dbl_3.bn.weight"        : "Mixed_5b.branch3x3dbl_3.bn.weight",
            "7.branch3x3dbl_3.conv.weight"      : "Mixed_5b.branch3x3dbl_3.conv.weight",
            "7.branch5x5_1.bn.bias"             : "Mixed_5b.branch5x5_1.bn.bias",
            "7.branch5x5_1.bn.running_mean"     : "Mixed_5b.branch5x5_1.bn.running_mean",
            "7.branch5x5_1.bn.running_var"      : "Mixed_5b.branch5x5_1.bn.running_var",
            "7.branch5x5_1.bn.weight"           : "Mixed_5b.branch5x5_1.bn.weight",
            "7.branch5x5_1.conv.weight"         : "Mixed_5b.branch5x5_1.conv.weight",
            "7.branch5x5_2.bn.bias"             : "Mixed_5b.branch5x5_2.bn.bias",
            "7.branch5x5_2.bn.running_mean"     : "Mixed_5b.branch5x5_2.bn.running_mean",
            "7.branch5x5_2.bn.running_var"      : "Mixed_5b.branch5x5_2.bn.running_var",
            "7.branch5x5_2.bn.weight"           : "Mixed_5b.branch5x5_2.bn.weight",
            "7.branch5x5_2.conv.weight"         : "Mixed_5b.branch5x5_2.conv.weight",
            "7.branch_pool.bn.bias"             : "Mixed_5b.branch_pool.bn.bias",
            "7.branch_pool.bn.running_mean"     : "Mixed_5b.branch_pool.bn.running_mean",
            "7.branch_pool.bn.running_var"      : "Mixed_5b.branch_pool.bn.running_var",
            "7.branch_pool.bn.weight"           : "Mixed_5b.branch_pool.bn.weight",
            "7.branch_pool.conv.weight"         : "Mixed_5b.branch_pool.conv.weight",
            "8.branch1x1.bn.bias"               : "Mixed_5c.branch1x1.bn.bias",
            "8.branch1x1.bn.running_mean"       : "Mixed_5c.branch1x1.bn.running_mean",
            "8.branch1x1.bn.running_var"        : "Mixed_5c.branch1x1.bn.running_var",
            "8.branch1x1.bn.weight"             : "Mixed_5c.branch1x1.bn.weight",
            "8.branch1x1.conv.weight"           : "Mixed_5c.branch1x1.conv.weight",
            "8.branch3x3dbl_1.bn.bias"          : "Mixed_5c.branch3x3dbl_1.bn.bias",
            "8.branch3x3dbl_1.bn.running_mean"  : "Mixed_5c.branch3x3dbl_1.bn.running_mean",
            "8.branch3x3dbl_1.bn.running_var"   : "Mixed_5c.branch3x3dbl_1.bn.running_var",
            "8.branch3x3dbl_1.bn.weight"        : "Mixed_5c.branch3x3dbl_1.bn.weight",
            "8.branch3x3dbl_1.conv.weight"      : "Mixed_5c.branch3x3dbl_1.conv.weight",
            "8.branch3x3dbl_2.bn.bias"          : "Mixed_5c.branch3x3dbl_2.bn.bias",
            "8.branch3x3dbl_2.bn.running_mean"  : "Mixed_5c.branch3x3dbl_2.bn.running_mean",
            "8.branch3x3dbl_2.bn.running_var"   : "Mixed_5c.branch3x3dbl_2.bn.running_var",
            "8.branch3x3dbl_2.bn.weight"        : "Mixed_5c.branch3x3dbl_2.bn.weight",
            "8.branch3x3dbl_2.conv.weight"      : "Mixed_5c.branch3x3dbl_2.conv.weight",
            "8.branch3x3dbl_3.bn.bias"          : "Mixed_5c.branch3x3dbl_3.bn.bias",
            "8.branch3x3dbl_3.bn.running_mean"  : "Mixed_5c.branch3x3dbl_3.bn.running_mean",
            "8.branch3x3dbl_3.bn.running_var"   : "Mixed_5c.branch3x3dbl_3.bn.running_var",
            "8.branch3x3dbl_3.bn.weight"        : "Mixed_5c.branch3x3dbl_3.bn.weight",
            "8.branch3x3dbl_3.conv.weight"      : "Mixed_5c.branch3x3dbl_3.conv.weight",
            "8.branch5x5_1.bn.bias"             : "Mixed_5c.branch5x5_1.bn.bias",
            "8.branch5x5_1.bn.running_mean"     : "Mixed_5c.branch5x5_1.bn.running_mean",
            "8.branch5x5_1.bn.running_var"      : "Mixed_5c.branch5x5_1.bn.running_var",
            "8.branch5x5_1.bn.weight"           : "Mixed_5c.branch5x5_1.bn.weight",
            "8.branch5x5_1.conv.weight"         : "Mixed_5c.branch5x5_1.conv.weight",
            "8.branch5x5_2.bn.bias"             : "Mixed_5c.branch5x5_2.bn.bias",
            "8.branch5x5_2.bn.running_mean"     : "Mixed_5c.branch5x5_2.bn.running_mean",
            "8.branch5x5_2.bn.running_var"      : "Mixed_5c.branch5x5_2.bn.running_var",
            "8.branch5x5_2.bn.weight"           : "Mixed_5c.branch5x5_2.bn.weight",
            "8.branch5x5_2.conv.weight"         : "Mixed_5c.branch5x5_2.conv.weight",
            "8.branch_pool.bn.bias"             : "Mixed_5c.branch_pool.bn.bias",
            "8.branch_pool.bn.running_mean"     : "Mixed_5c.branch_pool.bn.running_mean",
            "8.branch_pool.bn.running_var"      : "Mixed_5c.branch_pool.bn.running_var",
            "8.branch_pool.bn.weight"           : "Mixed_5c.branch_pool.bn.weight",
            "8.branch_pool.conv.weight"         : "Mixed_5c.branch_pool.conv.weight",
            "9.branch1x1.bn.bias"               : "Mixed_5d.branch1x1.bn.bias",
            "9.branch1x1.bn.running_mean"       : "Mixed_5d.branch1x1.bn.running_mean",
            "9.branch1x1.bn.running_var"        : "Mixed_5d.branch1x1.bn.running_var",
            "9.branch1x1.bn.weight"             : "Mixed_5d.branch1x1.bn.weight",
            "9.branch1x1.conv.weight"           : "Mixed_5d.branch1x1.conv.weight",
            "9.branch3x3dbl_1.bn.bias"          : "Mixed_5d.branch3x3dbl_1.bn.bias",
            "9.branch3x3dbl_1.bn.running_mean"  : "Mixed_5d.branch3x3dbl_1.bn.running_mean",
            "9.branch3x3dbl_1.bn.running_var"   : "Mixed_5d.branch3x3dbl_1.bn.running_var",
            "9.branch3x3dbl_1.bn.weight"        : "Mixed_5d.branch3x3dbl_1.bn.weight",
            "9.branch3x3dbl_1.conv.weight"      : "Mixed_5d.branch3x3dbl_1.conv.weight",
            "9.branch3x3dbl_2.bn.bias"          : "Mixed_5d.branch3x3dbl_2.bn.bias",
            "9.branch3x3dbl_2.bn.running_mean"  : "Mixed_5d.branch3x3dbl_2.bn.running_mean",
            "9.branch3x3dbl_2.bn.running_var"   : "Mixed_5d.branch3x3dbl_2.bn.running_var",
            "9.branch3x3dbl_2.bn.weight"        : "Mixed_5d.branch3x3dbl_2.bn.weight",
            "9.branch3x3dbl_2.conv.weight"      : "Mixed_5d.branch3x3dbl_2.conv.weight",
            "9.branch3x3dbl_3.bn.bias"          : "Mixed_5d.branch3x3dbl_3.bn.bias",
            "9.branch3x3dbl_3.bn.running_mean"  : "Mixed_5d.branch3x3dbl_3.bn.running_mean",
            "9.branch3x3dbl_3.bn.running_var"   : "Mixed_5d.branch3x3dbl_3.bn.running_var",
            "9.branch3x3dbl_3.bn.weight"        : "Mixed_5d.branch3x3dbl_3.bn.weight",
            "9.branch3x3dbl_3.conv.weight"      : "Mixed_5d.branch3x3dbl_3.conv.weight",
            "9.branch5x5_1.bn.bias"             : "Mixed_5d.branch5x5_1.bn.bias",
            "9.branch5x5_1.bn.running_mean"     : "Mixed_5d.branch5x5_1.bn.running_mean",
            "9.branch5x5_1.bn.running_var"      : "Mixed_5d.branch5x5_1.bn.running_var",
            "9.branch5x5_1.bn.weight"           : "Mixed_5d.branch5x5_1.bn.weight",
            "9.branch5x5_1.conv.weight"         : "Mixed_5d.branch5x5_1.conv.weight",
            "9.branch5x5_2.bn.bias"             : "Mixed_5d.branch5x5_2.bn.bias",
            "9.branch5x5_2.bn.running_mean"     : "Mixed_5d.branch5x5_2.bn.running_mean",
            "9.branch5x5_2.bn.running_var"      : "Mixed_5d.branch5x5_2.bn.running_var",
            "9.branch5x5_2.bn.weight"           : "Mixed_5d.branch5x5_2.bn.weight",
            "9.branch5x5_2.conv.weight"         : "Mixed_5d.branch5x5_2.conv.weight",
            "9.branch_pool.bn.bias"             : "Mixed_5d.branch_pool.bn.bias",
            "9.branch_pool.bn.running_mean"     : "Mixed_5d.branch_pool.bn.running_mean",
            "9.branch_pool.bn.running_var"      : "Mixed_5d.branch_pool.bn.running_var",
            "9.branch_pool.bn.weight"           : "Mixed_5d.branch_pool.bn.weight",
            "9.branch_pool.conv.weight"         : "Mixed_5d.branch_pool.conv.weight",
            "10.branch3x3.bn.bias"              : "Mixed_6a.branch3x3.bn.bias",
            "10.branch3x3.bn.running_mean"      : "Mixed_6a.branch3x3.bn.running_mean",
            "10.branch3x3.bn.running_var"       : "Mixed_6a.branch3x3.bn.running_var",
            "10.branch3x3.bn.weight"            : "Mixed_6a.branch3x3.bn.weight",
            "10.branch3x3.conv.weight"          : "Mixed_6a.branch3x3.conv.weight",
            "10.branch3x3dbl_1.bn.bias"         : "Mixed_6a.branch3x3dbl_1.bn.bias",
            "10.branch3x3dbl_1.bn.running_mean" : "Mixed_6a.branch3x3dbl_1.bn.running_mean",
            "10.branch3x3dbl_1.bn.running_var"  : "Mixed_6a.branch3x3dbl_1.bn.running_var",
            "10.branch3x3dbl_1.bn.weight"       : "Mixed_6a.branch3x3dbl_1.bn.weight",
            "10.branch3x3dbl_1.conv.weight"     : "Mixed_6a.branch3x3dbl_1.conv.weight",
            "10.branch3x3dbl_2.bn.bias"         : "Mixed_6a.branch3x3dbl_2.bn.bias",
            "10.branch3x3dbl_2.bn.running_mean" : "Mixed_6a.branch3x3dbl_2.bn.running_mean",
            "10.branch3x3dbl_2.bn.running_var"  : "Mixed_6a.branch3x3dbl_2.bn.running_var",
            "10.branch3x3dbl_2.bn.weight"       : "Mixed_6a.branch3x3dbl_2.bn.weight",
            "10.branch3x3dbl_2.conv.weight"     : "Mixed_6a.branch3x3dbl_2.conv.weight",
            "10.branch3x3dbl_3.bn.bias"         : "Mixed_6a.branch3x3dbl_3.bn.bias",
            "10.branch3x3dbl_3.bn.running_mean" : "Mixed_6a.branch3x3dbl_3.bn.running_mean",
            "10.branch3x3dbl_3.bn.running_var"  : "Mixed_6a.branch3x3dbl_3.bn.running_var",
            "10.branch3x3dbl_3.bn.weight"       : "Mixed_6a.branch3x3dbl_3.bn.weight",
            "10.branch3x3dbl_3.conv.weight"     : "Mixed_6a.branch3x3dbl_3.conv.weight",
            "11.branch1x1.bn.bias"              : "Mixed_6b.branch1x1.bn.bias",
            "11.branch1x1.bn.running_mean"      : "Mixed_6b.branch1x1.bn.running_mean",
            "11.branch1x1.bn.running_var"       : "Mixed_6b.branch1x1.bn.running_var",
            "11.branch1x1.bn.weight"            : "Mixed_6b.branch1x1.bn.weight",
            "11.branch1x1.conv.weight"          : "Mixed_6b.branch1x1.conv.weight",
            "11.branch7x7_1.bn.bias"            : "Mixed_6b.branch7x7_1.bn.bias",
            "11.branch7x7_1.bn.running_mean"    : "Mixed_6b.branch7x7_1.bn.running_mean",
            "11.branch7x7_1.bn.running_var"     : "Mixed_6b.branch7x7_1.bn.running_var",
            "11.branch7x7_1.bn.weight"          : "Mixed_6b.branch7x7_1.bn.weight",
            "11.branch7x7_1.conv.weight"        : "Mixed_6b.branch7x7_1.conv.weight",
            "11.branch7x7_2.bn.bias"            : "Mixed_6b.branch7x7_2.bn.bias",
            "11.branch7x7_2.bn.running_mean"    : "Mixed_6b.branch7x7_2.bn.running_mean",
            "11.branch7x7_2.bn.running_var"     : "Mixed_6b.branch7x7_2.bn.running_var",
            "11.branch7x7_2.bn.weight"          : "Mixed_6b.branch7x7_2.bn.weight",
            "11.branch7x7_2.conv.weight"        : "Mixed_6b.branch7x7_2.conv.weight",
            "11.branch7x7_3.bn.bias"            : "Mixed_6b.branch7x7_3.bn.bias",
            "11.branch7x7_3.bn.running_mean"    : "Mixed_6b.branch7x7_3.bn.running_mean",
            "11.branch7x7_3.bn.running_var"     : "Mixed_6b.branch7x7_3.bn.running_var",
            "11.branch7x7_3.bn.weight"          : "Mixed_6b.branch7x7_3.bn.weight",
            "11.branch7x7_3.conv.weight"        : "Mixed_6b.branch7x7_3.conv.weight",
            "11.branch7x7dbl_1.bn.bias"         : "Mixed_6b.branch7x7dbl_1.bn.bias",
            "11.branch7x7dbl_1.bn.running_mean" : "Mixed_6b.branch7x7dbl_1.bn.running_mean",
            "11.branch7x7dbl_1.bn.running_var"  : "Mixed_6b.branch7x7dbl_1.bn.running_var",
            "11.branch7x7dbl_1.bn.weight"       : "Mixed_6b.branch7x7dbl_1.bn.weight",
            "11.branch7x7dbl_1.conv.weight"     : "Mixed_6b.branch7x7dbl_1.conv.weight",
            "11.branch7x7dbl_2.bn.bias"         : "Mixed_6b.branch7x7dbl_2.bn.bias",
            "11.branch7x7dbl_2.bn.running_mean" : "Mixed_6b.branch7x7dbl_2.bn.running_mean",
            "11.branch7x7dbl_2.bn.running_var"  : "Mixed_6b.branch7x7dbl_2.bn.running_var",
            "11.branch7x7dbl_2.bn.weight"       : "Mixed_6b.branch7x7dbl_2.bn.weight",
            "11.branch7x7dbl_2.conv.weight"     : "Mixed_6b.branch7x7dbl_2.conv.weight",
            "11.branch7x7dbl_3.bn.bias"         : "Mixed_6b.branch7x7dbl_3.bn.bias",
            "11.branch7x7dbl_3.bn.running_mean" : "Mixed_6b.branch7x7dbl_3.bn.running_mean",
            "11.branch7x7dbl_3.bn.running_var"  : "Mixed_6b.branch7x7dbl_3.bn.running_var",
            "11.branch7x7dbl_3.bn.weight"       : "Mixed_6b.branch7x7dbl_3.bn.weight",
            "11.branch7x7dbl_3.conv.weight"     : "Mixed_6b.branch7x7dbl_3.conv.weight",
            "11.branch7x7dbl_4.bn.bias"         : "Mixed_6b.branch7x7dbl_4.bn.bias",
            "11.branch7x7dbl_4.bn.running_mean" : "Mixed_6b.branch7x7dbl_4.bn.running_mean",
            "11.branch7x7dbl_4.bn.running_var"  : "Mixed_6b.branch7x7dbl_4.bn.running_var",
            "11.branch7x7dbl_4.bn.weight"       : "Mixed_6b.branch7x7dbl_4.bn.weight",
            "11.branch7x7dbl_4.conv.weight"     : "Mixed_6b.branch7x7dbl_4.conv.weight",
            "11.branch7x7dbl_5.bn.bias"         : "Mixed_6b.branch7x7dbl_5.bn.bias",
            "11.branch7x7dbl_5.bn.running_mean" : "Mixed_6b.branch7x7dbl_5.bn.running_mean",
            "11.branch7x7dbl_5.bn.running_var"  : "Mixed_6b.branch7x7dbl_5.bn.running_var",
            "11.branch7x7dbl_5.bn.weight"       : "Mixed_6b.branch7x7dbl_5.bn.weight",
            "11.branch7x7dbl_5.conv.weight"     : "Mixed_6b.branch7x7dbl_5.conv.weight",
            "11.branch_pool.bn.bias"            : "Mixed_6b.branch_pool.bn.bias",
            "11.branch_pool.bn.running_mean"    : "Mixed_6b.branch_pool.bn.running_mean",
            "11.branch_pool.bn.running_var"     : "Mixed_6b.branch_pool.bn.running_var",
            "11.branch_pool.bn.weight"          : "Mixed_6b.branch_pool.bn.weight",
            "11.branch_pool.conv.weight"        : "Mixed_6b.branch_pool.conv.weight",
            "12.branch1x1.bn.bias"              : "Mixed_6c.branch1x1.bn.bias",
            "12.branch1x1.bn.running_mean"      : "Mixed_6c.branch1x1.bn.running_mean",
            "12.branch1x1.bn.running_var"       : "Mixed_6c.branch1x1.bn.running_var",
            "12.branch1x1.bn.weight"            : "Mixed_6c.branch1x1.bn.weight",
            "12.branch1x1.conv.weight"          : "Mixed_6c.branch1x1.conv.weight",
            "12.branch7x7_1.bn.bias"            : "Mixed_6c.branch7x7_1.bn.bias",
            "12.branch7x7_1.bn.running_mean"    : "Mixed_6c.branch7x7_1.bn.running_mean",
            "12.branch7x7_1.bn.running_var"     : "Mixed_6c.branch7x7_1.bn.running_var",
            "12.branch7x7_1.bn.weight"          : "Mixed_6c.branch7x7_1.bn.weight",
            "12.branch7x7_1.conv.weight"        : "Mixed_6c.branch7x7_1.conv.weight",
            "12.branch7x7_2.bn.bias"            : "Mixed_6c.branch7x7_2.bn.bias",
            "12.branch7x7_2.bn.running_mean"    : "Mixed_6c.branch7x7_2.bn.running_mean",
            "12.branch7x7_2.bn.running_var"     : "Mixed_6c.branch7x7_2.bn.running_var",
            "12.branch7x7_2.bn.weight"          : "Mixed_6c.branch7x7_2.bn.weight",
            "12.branch7x7_2.conv.weight"        : "Mixed_6c.branch7x7_2.conv.weight",
            "12.branch7x7_3.bn.bias"            : "Mixed_6c.branch7x7_3.bn.bias",
            "12.branch7x7_3.bn.running_mean"    : "Mixed_6c.branch7x7_3.bn.running_mean",
            "12.branch7x7_3.bn.running_var"     : "Mixed_6c.branch7x7_3.bn.running_var",
            "12.branch7x7_3.bn.weight"          : "Mixed_6c.branch7x7_3.bn.weight",
            "12.branch7x7_3.conv.weight"        : "Mixed_6c.branch7x7_3.conv.weight",
            "12.branch7x7dbl_1.bn.bias"         : "Mixed_6c.branch7x7dbl_1.bn.bias",
            "12.branch7x7dbl_1.bn.running_mean" : "Mixed_6c.branch7x7dbl_1.bn.running_mean",
            "12.branch7x7dbl_1.bn.running_var"  : "Mixed_6c.branch7x7dbl_1.bn.running_var",
            "12.branch7x7dbl_1.bn.weight"       : "Mixed_6c.branch7x7dbl_1.bn.weight",
            "12.branch7x7dbl_1.conv.weight"     : "Mixed_6c.branch7x7dbl_1.conv.weight",
            "12.branch7x7dbl_2.bn.bias"         : "Mixed_6c.branch7x7dbl_2.bn.bias",
            "12.branch7x7dbl_2.bn.running_mean" : "Mixed_6c.branch7x7dbl_2.bn.running_mean",
            "12.branch7x7dbl_2.bn.running_var"  : "Mixed_6c.branch7x7dbl_2.bn.running_var",
            "12.branch7x7dbl_2.bn.weight"       : "Mixed_6c.branch7x7dbl_2.bn.weight",
            "12.branch7x7dbl_2.conv.weight"     : "Mixed_6c.branch7x7dbl_2.conv.weight",
            "12.branch7x7dbl_3.bn.bias"         : "Mixed_6c.branch7x7dbl_3.bn.bias",
            "12.branch7x7dbl_3.bn.running_mean" : "Mixed_6c.branch7x7dbl_3.bn.running_mean",
            "12.branch7x7dbl_3.bn.running_var"  : "Mixed_6c.branch7x7dbl_3.bn.running_var",
            "12.branch7x7dbl_3.bn.weight"       : "Mixed_6c.branch7x7dbl_3.bn.weight",
            "12.branch7x7dbl_3.conv.weight"     : "Mixed_6c.branch7x7dbl_3.conv.weight",
            "12.branch7x7dbl_4.bn.bias"         : "Mixed_6c.branch7x7dbl_4.bn.bias",
            "12.branch7x7dbl_4.bn.running_mean" : "Mixed_6c.branch7x7dbl_4.bn.running_mean",
            "12.branch7x7dbl_4.bn.running_var"  : "Mixed_6c.branch7x7dbl_4.bn.running_var",
            "12.branch7x7dbl_4.bn.weight"       : "Mixed_6c.branch7x7dbl_4.bn.weight",
            "12.branch7x7dbl_4.conv.weight"     : "Mixed_6c.branch7x7dbl_4.conv.weight",
            "12.branch7x7dbl_5.bn.bias"         : "Mixed_6c.branch7x7dbl_5.bn.bias",
            "12.branch7x7dbl_5.bn.running_mean" : "Mixed_6c.branch7x7dbl_5.bn.running_mean",
            "12.branch7x7dbl_5.bn.running_var"  : "Mixed_6c.branch7x7dbl_5.bn.running_var",
            "12.branch7x7dbl_5.bn.weight"       : "Mixed_6c.branch7x7dbl_5.bn.weight",
            "12.branch7x7dbl_5.conv.weight"     : "Mixed_6c.branch7x7dbl_5.conv.weight",
            "12.branch_pool.bn.bias"            : "Mixed_6c.branch_pool.bn.bias",
            "12.branch_pool.bn.running_mean"    : "Mixed_6c.branch_pool.bn.running_mean",
            "12.branch_pool.bn.running_var"     : "Mixed_6c.branch_pool.bn.running_var",
            "12.branch_pool.bn.weight"          : "Mixed_6c.branch_pool.bn.weight",
            "12.branch_pool.conv.weight"        : "Mixed_6c.branch_pool.conv.weight",
            "13.branch1x1.bn.bias"              : "Mixed_6d.branch1x1.bn.bias",
            "13.branch1x1.bn.running_mean"      : "Mixed_6d.branch1x1.bn.running_mean",
            "13.branch1x1.bn.running_var"       : "Mixed_6d.branch1x1.bn.running_var",
            "13.branch1x1.bn.weight"            : "Mixed_6d.branch1x1.bn.weight",
            "13.branch1x1.conv.weight"          : "Mixed_6d.branch1x1.conv.weight",
            "13.branch7x7_1.bn.bias"            : "Mixed_6d.branch7x7_1.bn.bias",
            "13.branch7x7_1.bn.running_mean"    : "Mixed_6d.branch7x7_1.bn.running_mean",
            "13.branch7x7_1.bn.running_var"     : "Mixed_6d.branch7x7_1.bn.running_var",
            "13.branch7x7_1.bn.weight"          : "Mixed_6d.branch7x7_1.bn.weight",
            "13.branch7x7_1.conv.weight"        : "Mixed_6d.branch7x7_1.conv.weight",
            "13.branch7x7_2.bn.bias"            : "Mixed_6d.branch7x7_2.bn.bias",
            "13.branch7x7_2.bn.running_mean"    : "Mixed_6d.branch7x7_2.bn.running_mean",
            "13.branch7x7_2.bn.running_var"     : "Mixed_6d.branch7x7_2.bn.running_var",
            "13.branch7x7_2.bn.weight"          : "Mixed_6d.branch7x7_2.bn.weight",
            "13.branch7x7_2.conv.weight"        : "Mixed_6d.branch7x7_2.conv.weight",
            "13.branch7x7_3.bn.bias"            : "Mixed_6d.branch7x7_3.bn.bias",
            "13.branch7x7_3.bn.running_mean"    : "Mixed_6d.branch7x7_3.bn.running_mean",
            "13.branch7x7_3.bn.running_var"     : "Mixed_6d.branch7x7_3.bn.running_var",
            "13.branch7x7_3.bn.weight"          : "Mixed_6d.branch7x7_3.bn.weight",
            "13.branch7x7_3.conv.weight"        : "Mixed_6d.branch7x7_3.conv.weight",
            "13.branch7x7dbl_1.bn.bias"         : "Mixed_6d.branch7x7dbl_1.bn.bias",
            "13.branch7x7dbl_1.bn.running_mean" : "Mixed_6d.branch7x7dbl_1.bn.running_mean",
            "13.branch7x7dbl_1.bn.running_var"  : "Mixed_6d.branch7x7dbl_1.bn.running_var",
            "13.branch7x7dbl_1.bn.weight"       : "Mixed_6d.branch7x7dbl_1.bn.weight",
            "13.branch7x7dbl_1.conv.weight"     : "Mixed_6d.branch7x7dbl_1.conv.weight",
            "13.branch7x7dbl_2.bn.bias"         : "Mixed_6d.branch7x7dbl_2.bn.bias",
            "13.branch7x7dbl_2.bn.running_mean" : "Mixed_6d.branch7x7dbl_2.bn.running_mean",
            "13.branch7x7dbl_2.bn.running_var"  : "Mixed_6d.branch7x7dbl_2.bn.running_var",
            "13.branch7x7dbl_2.bn.weight"       : "Mixed_6d.branch7x7dbl_2.bn.weight",
            "13.branch7x7dbl_2.conv.weight"     : "Mixed_6d.branch7x7dbl_2.conv.weight",
            "13.branch7x7dbl_3.bn.bias"         : "Mixed_6d.branch7x7dbl_3.bn.bias",
            "13.branch7x7dbl_3.bn.running_mean" : "Mixed_6d.branch7x7dbl_3.bn.running_mean",
            "13.branch7x7dbl_3.bn.running_var"  : "Mixed_6d.branch7x7dbl_3.bn.running_var",
            "13.branch7x7dbl_3.bn.weight"       : "Mixed_6d.branch7x7dbl_3.bn.weight",
            "13.branch7x7dbl_3.conv.weight"     : "Mixed_6d.branch7x7dbl_3.conv.weight",
            "13.branch7x7dbl_4.bn.bias"         : "Mixed_6d.branch7x7dbl_4.bn.bias",
            "13.branch7x7dbl_4.bn.running_mean" : "Mixed_6d.branch7x7dbl_4.bn.running_mean",
            "13.branch7x7dbl_4.bn.running_var"  : "Mixed_6d.branch7x7dbl_4.bn.running_var",
            "13.branch7x7dbl_4.bn.weight"       : "Mixed_6d.branch7x7dbl_4.bn.weight",
            "13.branch7x7dbl_4.conv.weight"     : "Mixed_6d.branch7x7dbl_4.conv.weight",
            "13.branch7x7dbl_5.bn.bias"         : "Mixed_6d.branch7x7dbl_5.bn.bias",
            "13.branch7x7dbl_5.bn.running_mean" : "Mixed_6d.branch7x7dbl_5.bn.running_mean",
            "13.branch7x7dbl_5.bn.running_var"  : "Mixed_6d.branch7x7dbl_5.bn.running_var",
            "13.branch7x7dbl_5.bn.weight"       : "Mixed_6d.branch7x7dbl_5.bn.weight",
            "13.branch7x7dbl_5.conv.weight"     : "Mixed_6d.branch7x7dbl_5.conv.weight",
            "13.branch_pool.bn.bias"            : "Mixed_6d.branch_pool.bn.bias",
            "13.branch_pool.bn.running_mean"    : "Mixed_6d.branch_pool.bn.running_mean",
            "13.branch_pool.bn.running_var"     : "Mixed_6d.branch_pool.bn.running_var",
            "13.branch_pool.bn.weight"          : "Mixed_6d.branch_pool.bn.weight",
            "13.branch_pool.conv.weight"        : "Mixed_6d.branch_pool.conv.weight",
            "14.branch1x1.bn.bias"              : "Mixed_6e.branch1x1.bn.bias",
            "14.branch1x1.bn.running_mean"      : "Mixed_6e.branch1x1.bn.running_mean",
            "14.branch1x1.bn.running_var"       : "Mixed_6e.branch1x1.bn.running_var",
            "14.branch1x1.bn.weight"            : "Mixed_6e.branch1x1.bn.weight",
            "14.branch1x1.conv.weight"          : "Mixed_6e.branch1x1.conv.weight",
            "14.branch7x7_1.bn.bias"            : "Mixed_6e.branch7x7_1.bn.bias",
            "14.branch7x7_1.bn.running_mean"    : "Mixed_6e.branch7x7_1.bn.running_mean",
            "14.branch7x7_1.bn.running_var"     : "Mixed_6e.branch7x7_1.bn.running_var",
            "14.branch7x7_1.bn.weight"          : "Mixed_6e.branch7x7_1.bn.weight",
            "14.branch7x7_1.conv.weight"        : "Mixed_6e.branch7x7_1.conv.weight",
            "14.branch7x7_2.bn.bias"            : "Mixed_6e.branch7x7_2.bn.bias",
            "14.branch7x7_2.bn.running_mean"    : "Mixed_6e.branch7x7_2.bn.running_mean",
            "14.branch7x7_2.bn.running_var"     : "Mixed_6e.branch7x7_2.bn.running_var",
            "14.branch7x7_2.bn.weight"          : "Mixed_6e.branch7x7_2.bn.weight",
            "14.branch7x7_2.conv.weight"        : "Mixed_6e.branch7x7_2.conv.weight",
            "14.branch7x7_3.bn.bias"            : "Mixed_6e.branch7x7_3.bn.bias",
            "14.branch7x7_3.bn.running_mean"    : "Mixed_6e.branch7x7_3.bn.running_mean",
            "14.branch7x7_3.bn.running_var"     : "Mixed_6e.branch7x7_3.bn.running_var",
            "14.branch7x7_3.bn.weight"          : "Mixed_6e.branch7x7_3.bn.weight",
            "14.branch7x7_3.conv.weight"        : "Mixed_6e.branch7x7_3.conv.weight",
            "14.branch7x7dbl_1.bn.bias"         : "Mixed_6e.branch7x7dbl_1.bn.bias",
            "14.branch7x7dbl_1.bn.running_mean" : "Mixed_6e.branch7x7dbl_1.bn.running_mean",
            "14.branch7x7dbl_1.bn.running_var"  : "Mixed_6e.branch7x7dbl_1.bn.running_var",
            "14.branch7x7dbl_1.bn.weight"       : "Mixed_6e.branch7x7dbl_1.bn.weight",
            "14.branch7x7dbl_1.conv.weight"     : "Mixed_6e.branch7x7dbl_1.conv.weight",
            "14.branch7x7dbl_2.bn.bias"         : "Mixed_6e.branch7x7dbl_2.bn.bias",
            "14.branch7x7dbl_2.bn.running_mean" : "Mixed_6e.branch7x7dbl_2.bn.running_mean",
            "14.branch7x7dbl_2.bn.running_var"  : "Mixed_6e.branch7x7dbl_2.bn.running_var",
            "14.branch7x7dbl_2.bn.weight"       : "Mixed_6e.branch7x7dbl_2.bn.weight",
            "14.branch7x7dbl_2.conv.weight"     : "Mixed_6e.branch7x7dbl_2.conv.weight",
            "14.branch7x7dbl_3.bn.bias"         : "Mixed_6e.branch7x7dbl_3.bn.bias",
            "14.branch7x7dbl_3.bn.running_mean" : "Mixed_6e.branch7x7dbl_3.bn.running_mean",
            "14.branch7x7dbl_3.bn.running_var"  : "Mixed_6e.branch7x7dbl_3.bn.running_var",
            "14.branch7x7dbl_3.bn.weight"       : "Mixed_6e.branch7x7dbl_3.bn.weight",
            "14.branch7x7dbl_3.conv.weight"     : "Mixed_6e.branch7x7dbl_3.conv.weight",
            "14.branch7x7dbl_4.bn.bias"         : "Mixed_6e.branch7x7dbl_4.bn.bias",
            "14.branch7x7dbl_4.bn.running_mean" : "Mixed_6e.branch7x7dbl_4.bn.running_mean",
            "14.branch7x7dbl_4.bn.running_var"  : "Mixed_6e.branch7x7dbl_4.bn.running_var",
            "14.branch7x7dbl_4.bn.weight"       : "Mixed_6e.branch7x7dbl_4.bn.weight",
            "14.branch7x7dbl_4.conv.weight"     : "Mixed_6e.branch7x7dbl_4.conv.weight",
            "14.branch7x7dbl_5.bn.bias"         : "Mixed_6e.branch7x7dbl_5.bn.bias",
            "14.branch7x7dbl_5.bn.running_mean" : "Mixed_6e.branch7x7dbl_5.bn.running_mean",
            "14.branch7x7dbl_5.bn.running_var"  : "Mixed_6e.branch7x7dbl_5.bn.running_var",
            "14.branch7x7dbl_5.bn.weight"       : "Mixed_6e.branch7x7dbl_5.bn.weight",
            "14.branch7x7dbl_5.conv.weight"     : "Mixed_6e.branch7x7dbl_5.conv.weight",
            "14.branch_pool.bn.bias"            : "Mixed_6e.branch_pool.bn.bias",
            "14.branch_pool.bn.running_mean"    : "Mixed_6e.branch_pool.bn.running_mean",
            "14.branch_pool.bn.running_var"     : "Mixed_6e.branch_pool.bn.running_var",
            "14.branch_pool.bn.weight"          : "Mixed_6e.branch_pool.bn.weight",
            "14.branch_pool.conv.weight"        : "Mixed_6e.branch_pool.conv.weight",
            "15.conv0.bn.bias"                  : "AuxLogits.conv0.bn.bias",
            "15.conv0.bn.running_mean"          : "AuxLogits.conv0.bn.running_mean",
            "15.conv0.bn.running_var"           : "AuxLogits.conv0.bn.running_var",
            "15.conv0.bn.weight"                : "AuxLogits.conv0.bn.weight",
            "15.conv0.conv.weight"              : "AuxLogits.conv0.conv.weight",
            "15.conv1.bn.bias"                  : "AuxLogits.conv1.bn.bias",
            "15.conv1.bn.running_mean"          : "AuxLogits.conv1.bn.running_mean",
            "15.conv1.bn.running_var"           : "AuxLogits.conv1.bn.running_var",
            "15.conv1.bn.weight"                : "AuxLogits.conv1.bn.weight",
            "15.conv1.conv.weight"              : "AuxLogits.conv1.conv.weight",
            "15.fc.bias"                        : "AuxLogits.fc.bias",
            "15.fc.weight"                      : "AuxLogits.fc.weight",
            "16.branch3x3_1.bn.bias"            : "Mixed_7a.branch3x3_1.bn.bias",
            "16.branch3x3_1.bn.running_mean"    : "Mixed_7a.branch3x3_1.bn.running_mean",
            "16.branch3x3_1.bn.running_var"     : "Mixed_7a.branch3x3_1.bn.running_var",
            "16.branch3x3_1.bn.weight"          : "Mixed_7a.branch3x3_1.bn.weight",
            "16.branch3x3_1.conv.weight"        : "Mixed_7a.branch3x3_1.conv.weight",
            "16.branch3x3_2.bn.bias"            : "Mixed_7a.branch3x3_2.bn.bias",
            "16.branch3x3_2.bn.running_mean"    : "Mixed_7a.branch3x3_2.bn.running_mean",
            "16.branch3x3_2.bn.running_var"     : "Mixed_7a.branch3x3_2.bn.running_var",
            "16.branch3x3_2.bn.weight"          : "Mixed_7a.branch3x3_2.bn.weight",
            "16.branch3x3_2.conv.weight"        : "Mixed_7a.branch3x3_2.conv.weight",
            "16.branch7x7x3_1.bn.bias"          : "Mixed_7a.branch7x7x3_1.bn.bias",
            "16.branch7x7x3_1.bn.running_mean"  : "Mixed_7a.branch7x7x3_1.bn.running_mean",
            "16.branch7x7x3_1.bn.running_var"   : "Mixed_7a.branch7x7x3_1.bn.running_var",
            "16.branch7x7x3_1.bn.weight"        : "Mixed_7a.branch7x7x3_1.bn.weight",
            "16.branch7x7x3_1.conv.weight"      : "Mixed_7a.branch7x7x3_1.conv.weight",
            "16.branch7x7x3_2.bn.bias"          : "Mixed_7a.branch7x7x3_2.bn.bias",
            "16.branch7x7x3_2.bn.running_mean"  : "Mixed_7a.branch7x7x3_2.bn.running_mean",
            "16.branch7x7x3_2.bn.running_var"   : "Mixed_7a.branch7x7x3_2.bn.running_var",
            "16.branch7x7x3_2.bn.weight"        : "Mixed_7a.branch7x7x3_2.bn.weight",
            "16.branch7x7x3_2.conv.weight"      : "Mixed_7a.branch7x7x3_2.conv.weight",
            "16.branch7x7x3_3.bn.bias"          : "Mixed_7a.branch7x7x3_3.bn.bias",
            "16.branch7x7x3_3.bn.running_mean"  : "Mixed_7a.branch7x7x3_3.bn.running_mean",
            "16.branch7x7x3_3.bn.running_var"   : "Mixed_7a.branch7x7x3_3.bn.running_var",
            "16.branch7x7x3_3.bn.weight"        : "Mixed_7a.branch7x7x3_3.bn.weight",
            "16.branch7x7x3_3.conv.weight"      : "Mixed_7a.branch7x7x3_3.conv.weight",
            "16.branch7x7x3_4.bn.bias"          : "Mixed_7a.branch7x7x3_4.bn.bias",
            "16.branch7x7x3_4.bn.running_mean"  : "Mixed_7a.branch7x7x3_4.bn.running_mean",
            "16.branch7x7x3_4.bn.running_var"   : "Mixed_7a.branch7x7x3_4.bn.running_var",
            "16.branch7x7x3_4.bn.weight"        : "Mixed_7a.branch7x7x3_4.bn.weight",
            "16.branch7x7x3_4.conv.weight"      : "Mixed_7a.branch7x7x3_4.conv.weight",
            "17.branch1x1.bn.bias"              : "Mixed_7b.branch1x1.bn.bias",
            "17.branch1x1.bn.running_mean"      : "Mixed_7b.branch1x1.bn.running_mean",
            "17.branch1x1.bn.running_var"       : "Mixed_7b.branch1x1.bn.running_var",
            "17.branch1x1.bn.weight"            : "Mixed_7b.branch1x1.bn.weight",
            "17.branch1x1.conv.weight"          : "Mixed_7b.branch1x1.conv.weight",
            "17.branch3x3_1.bn.bias"            : "Mixed_7b.branch3x3_1.bn.bias",
            "17.branch3x3_1.bn.running_mean"    : "Mixed_7b.branch3x3_1.bn.running_mean",
            "17.branch3x3_1.bn.running_var"     : "Mixed_7b.branch3x3_1.bn.running_var",
            "17.branch3x3_1.bn.weight"          : "Mixed_7b.branch3x3_1.bn.weight",
            "17.branch3x3_1.conv.weight"        : "Mixed_7b.branch3x3_1.conv.weight",
            "17.branch3x3_2a.bn.bias"           : "Mixed_7b.branch3x3_2a.bn.bias",
            "17.branch3x3_2a.bn.running_mean"   : "Mixed_7b.branch3x3_2a.bn.running_mean",
            "17.branch3x3_2a.bn.running_var"    : "Mixed_7b.branch3x3_2a.bn.running_var",
            "17.branch3x3_2a.bn.weight"         : "Mixed_7b.branch3x3_2a.bn.weight",
            "17.branch3x3_2a.conv.weight"       : "Mixed_7b.branch3x3_2a.conv.weight",
            "17.branch3x3_2b.bn.bias"           : "Mixed_7b.branch3x3_2b.bn.bias",
            "17.branch3x3_2b.bn.running_mean"   : "Mixed_7b.branch3x3_2b.bn.running_mean",
            "17.branch3x3_2b.bn.running_var"    : "Mixed_7b.branch3x3_2b.bn.running_var",
            "17.branch3x3_2b.bn.weight"         : "Mixed_7b.branch3x3_2b.bn.weight",
            "17.branch3x3_2b.conv.weight"       : "Mixed_7b.branch3x3_2b.conv.weight",
            "17.branch3x3dbl_1.bn.bias"         : "Mixed_7b.branch3x3dbl_1.bn.bias",
            "17.branch3x3dbl_1.bn.running_mean" : "Mixed_7b.branch3x3dbl_1.bn.running_mean",
            "17.branch3x3dbl_1.bn.running_var"  : "Mixed_7b.branch3x3dbl_1.bn.running_var",
            "17.branch3x3dbl_1.bn.weight"       : "Mixed_7b.branch3x3dbl_1.bn.weight",
            "17.branch3x3dbl_1.conv.weight"     : "Mixed_7b.branch3x3dbl_1.conv.weight",
            "17.branch3x3dbl_2.bn.bias"         : "Mixed_7b.branch3x3dbl_2.bn.bias",
            "17.branch3x3dbl_2.bn.running_mean" : "Mixed_7b.branch3x3dbl_2.bn.running_mean",
            "17.branch3x3dbl_2.bn.running_var"  : "Mixed_7b.branch3x3dbl_2.bn.running_var",
            "17.branch3x3dbl_2.bn.weight"       : "Mixed_7b.branch3x3dbl_2.bn.weight",
            "17.branch3x3dbl_2.conv.weight"     : "Mixed_7b.branch3x3dbl_2.conv.weight",
            "17.branch3x3dbl_3a.bn.bias"        : "Mixed_7b.branch3x3dbl_3a.bn.bias",
            "17.branch3x3dbl_3a.bn.running_mean": "Mixed_7b.branch3x3dbl_3a.bn.running_mean",
            "17.branch3x3dbl_3a.bn.running_var" : "Mixed_7b.branch3x3dbl_3a.bn.running_var",
            "17.branch3x3dbl_3a.bn.weight"      : "Mixed_7b.branch3x3dbl_3a.bn.weight",
            "17.branch3x3dbl_3a.conv.weight"    : "Mixed_7b.branch3x3dbl_3a.conv.weight",
            "17.branch3x3dbl_3b.bn.bias"        : "Mixed_7b.branch3x3dbl_3b.bn.bias",
            "17.branch3x3dbl_3b.bn.running_mean": "Mixed_7b.branch3x3dbl_3b.bn.running_mean",
            "17.branch3x3dbl_3b.bn.running_var" : "Mixed_7b.branch3x3dbl_3b.bn.running_var",
            "17.branch3x3dbl_3b.bn.weight"      : "Mixed_7b.branch3x3dbl_3b.bn.weight",
            "17.branch3x3dbl_3b.conv.weight"    : "Mixed_7b.branch3x3dbl_3b.conv.weight",
            "17.branch_pool.bn.bias"            : "Mixed_7b.branch_pool.bn.bias",
            "17.branch_pool.bn.running_mean"    : "Mixed_7b.branch_pool.bn.running_mean",
            "17.branch_pool.bn.running_var"     : "Mixed_7b.branch_pool.bn.running_var",
            "17.branch_pool.bn.weight"          : "Mixed_7b.branch_pool.bn.weight",
            "17.branch_pool.conv.weight"        : "Mixed_7b.branch_pool.conv.weight",
            "18.branch1x1.bn.bias"              : "Mixed_7c.branch1x1.bn.bias",
            "18.branch1x1.bn.running_mean"      : "Mixed_7c.branch1x1.bn.running_mean",
            "18.branch1x1.bn.running_var"       : "Mixed_7c.branch1x1.bn.running_var",
            "18.branch1x1.bn.weight"            : "Mixed_7c.branch1x1.bn.weight",
            "18.branch1x1.conv.weight"          : "Mixed_7c.branch1x1.conv.weight",
            "18.branch3x3_1.bn.bias"            : "Mixed_7c.branch3x3_1.bn.bias",
            "18.branch3x3_1.bn.running_mean"    : "Mixed_7c.branch3x3_1.bn.running_mean",
            "18.branch3x3_1.bn.running_var"     : "Mixed_7c.branch3x3_1.bn.running_var",
            "18.branch3x3_1.bn.weight"          : "Mixed_7c.branch3x3_1.bn.weight",
            "18.branch3x3_1.conv.weight"        : "Mixed_7c.branch3x3_1.conv.weight",
            "18.branch3x3_2a.bn.bias"           : "Mixed_7c.branch3x3_2a.bn.bias",
            "18.branch3x3_2a.bn.running_mean"   : "Mixed_7c.branch3x3_2a.bn.running_mean",
            "18.branch3x3_2a.bn.running_var"    : "Mixed_7c.branch3x3_2a.bn.running_var",
            "18.branch3x3_2a.bn.weight"         : "Mixed_7c.branch3x3_2a.bn.weight",
            "18.branch3x3_2a.conv.weight"       : "Mixed_7c.branch3x3_2a.conv.weight",
            "18.branch3x3_2b.bn.bias"           : "Mixed_7c.branch3x3_2b.bn.bias",
            "18.branch3x3_2b.bn.running_mean"   : "Mixed_7c.branch3x3_2b.bn.running_mean",
            "18.branch3x3_2b.bn.running_var"    : "Mixed_7c.branch3x3_2b.bn.running_var",
            "18.branch3x3_2b.bn.weight"         : "Mixed_7c.branch3x3_2b.bn.weight",
            "18.branch3x3_2b.conv.weight"       : "Mixed_7c.branch3x3_2b.conv.weight",
            "18.branch3x3dbl_1.bn.bias"         : "Mixed_7c.branch3x3dbl_1.bn.bias",
            "18.branch3x3dbl_1.bn.running_mean" : "Mixed_7c.branch3x3dbl_1.bn.running_mean",
            "18.branch3x3dbl_1.bn.running_var"  : "Mixed_7c.branch3x3dbl_1.bn.running_var",
            "18.branch3x3dbl_1.bn.weight"       : "Mixed_7c.branch3x3dbl_1.bn.weight",
            "18.branch3x3dbl_1.conv.weight"     : "Mixed_7c.branch3x3dbl_1.conv.weight",
            "18.branch3x3dbl_2.bn.bias"         : "Mixed_7c.branch3x3dbl_2.bn.bias",
            "18.branch3x3dbl_2.bn.running_mean" : "Mixed_7c.branch3x3dbl_2.bn.running_mean",
            "18.branch3x3dbl_2.bn.running_var"  : "Mixed_7c.branch3x3dbl_2.bn.running_var",
            "18.branch3x3dbl_2.bn.weight"       : "Mixed_7c.branch3x3dbl_2.bn.weight",
            "18.branch3x3dbl_2.conv.weight"     : "Mixed_7c.branch3x3dbl_2.conv.weight",
            "18.branch3x3dbl_3a.bn.bias"        : "Mixed_7c.branch3x3dbl_3a.bn.bias",
            "18.branch3x3dbl_3a.bn.running_mean": "Mixed_7c.branch3x3dbl_3a.bn.running_mean",
            "18.branch3x3dbl_3a.bn.running_var" : "Mixed_7c.branch3x3dbl_3a.bn.running_var",
            "18.branch3x3dbl_3a.bn.weight"      : "Mixed_7c.branch3x3dbl_3a.bn.weight",
            "18.branch3x3dbl_3a.conv.weight"    : "Mixed_7c.branch3x3dbl_3a.conv.weight",
            "18.branch3x3dbl_3b.bn.bias"        : "Mixed_7c.branch3x3dbl_3b.bn.bias",
            "18.branch3x3dbl_3b.bn.running_mean": "Mixed_7c.branch3x3dbl_3b.bn.running_mean",
            "18.branch3x3dbl_3b.bn.running_var" : "Mixed_7c.branch3x3dbl_3b.bn.running_var",
            "18.branch3x3dbl_3b.bn.weight"      : "Mixed_7c.branch3x3dbl_3b.bn.weight",
            "18.branch3x3dbl_3b.conv.weight"    : "Mixed_7c.branch3x3dbl_3b.conv.weight",
            "18.branch_pool.bn.bias"            : "Mixed_7c.branch_pool.bn.bias",
            "18.branch_pool.bn.running_mean"    : "Mixed_7c.branch_pool.bn.running_mean",
            "18.branch_pool.bn.running_var"     : "Mixed_7c.branch_pool.bn.running_var",
            "18.branch_pool.bn.weight"          : "Mixed_7c.branch_pool.bn.weight",
            "18.branch_pool.conv.weight"        : "Mixed_7c.branch_pool.conv.weight",
        },
        "head"    : {
            "19.fc.bias"  : "fc.bias",
            "19.fc.weight": "fc.weight",
        },
    }

    def __init__(self, *args, **kwargs):
        kwargs |= {
            "config" : "inception3.yaml",
            "name"   : "inception",
            "variant": "inception3"
        }
        super().__init__(*args, **kwargs)
    
    def init_weights(self, m: torch.nn.Module):
        classname    = m.__class__.__name__
        init_weights = self.config["zero_init_residual"]
        if init_weights:
            if isinstance(m, torch.nn.Conv2d) or isinstance(m, torch.nn.Linear):
                stddev = float(m.stddev) if hasattr(m, "stddev") else 0.1  # type: ignore
                torch.nn.init.trunc_normal_(m.weight, mean=0.0, std=stddev, a=-2, b=2)
            elif isinstance(m, torch.nn.BatchNorm2d):
                torch.nn.init.constant_(m.weight, 1)
                torch.nn.init.constant_(m.bias,   0)
    
    def load_weights(self):
        """Load weights. It only loads the intersection layers of matching keys
        and shapes between the current model and weights.
        """
        if isinstance(self.weights, dict) \
            and self.weights["name"] in ["imagenet"]:
            state_dict = mmodel.load_state_dict_from_path(
                model_dir=self.zoo_dir, **self.weights
            )
            model_state_dict = self.model.state_dict()
            """
            for k in self.model.state_dict().keys():
                print(f"\"{k}\": ")
            for k in state_dict.keys():
                print(f"\"{k}\"")
            """
            for k, v in self.map_weights["backbone"].items():
                model_state_dict[k] = state_dict[v]
            if self.weights["num_classes"] == self.num_classes:
                for k, v in self.map_weights["head"].items():
                    model_state_dict[k] = state_dict[v]
            self.model.load_state_dict(model_state_dict)
        else:
            super().load_weights()
        
# endregion
