#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""A package for optimization algorithms and learning rate schedulers.

This package provides various optimization algorithms and learning rate schedulers
commonly used in training machine learning models.
"""

__all__ = [
    "ASGD",
    "Adadelta",
    "Adafactor",
    "Adagrad",
    "Adam",
    "AdamW",
    "Adamax",
    "ChainedScheduler",
    "ConstantLR",
    "CosineAnnealingLR",
    "CosineAnnealingWarmRestarts",
    "CyclicLR",
    "ExponentialLR",
    "LBFGS",
    "LRScheduler",
    "LambdaLR",
    "LinearLR",
    "MultiStepLR",
    "MultiplicativeLR",
    "NAdam",
    "OneCycleLR",
    "Optimizer",
    "PolynomialLR",
    "RAdam",
    "RMSprop",
    "ReduceLROnPlateau",
    "Rprop",
    "SGD",
    "SequentialLR",
    "SparseAdam",
    "StepLR",
    # "lr_scheduler",
    # "swa_utils",
]

from .core import (
    Adadelta,
    Adafactor,
    Adagrad,
    Adam,
    Adamax,
    AdamW,
    ASGD,
    ChainedScheduler,
    ConstantLR,
    CosineAnnealingLR,
    CosineAnnealingWarmRestarts,
    CyclicLR,
    ExponentialLR,
    LambdaLR,
    LBFGS,
    LinearLR,
    LRScheduler,
    MultiplicativeLR,
    MultiStepLR,
    NAdam,
    OneCycleLR,
    Optimizer,
    PolynomialLR,
    RAdam,
    ReduceLROnPlateau,
    RMSprop,
    Rprop,
    SequentialLR,
    SGD,
    SparseAdam,
    StepLR,
)
