# - Add conda-forge channel
#   conda config --append channels conda-forge
#
# - Install:
#   conda env create -f environment.yml
# 
# - Install cudatoolkit separately:
#   conda install cudatoolkit=11.3
#
# - Install PyTorch separately:
#   conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch -c conda-forge
#
# - Update:
#   conda env update --name base --file environment.yml
#
# - Update all pip packages:
#   pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
#

name: base

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - cudatoolkit=11.3
  # - cudatoolkit-dev=11.3
  - cudnn
    # CUDA is a parallel computing platform and programming model developed by
    # NVIDIA for general computing on graphical processing units (GPUs).
  - git
  - git-lfs
    # Git
  - librsvg
  - libiconv
  - python=3.9
    # Python
  - pyqt
    # Qt
  - pip
  - pip:
        - cython
          # The Cython language is a superset of the Python language that
          # additionally supports calling C functions and declaring C types on
          # variables and class attributes.
        - ffmpeg-python
          # Python bindings for FFmpeg.
        - filterpy
          # FilterPy is a Python library that implements a number of Bayesian
          # filtering, most notably Kalman filtering.
        - koila
          # Koila solves CUDA error: out of memory error painlessly.
          # Fix it with just one line of code, and forget it.
          # https://github.com/rentruewang/koila
        - labelImg
          # LabelImg is a graphical image annotation tool.
          # https://github.com/tzutalin/labelImg
        - labelme
          # Image Polygonal Annotation with Python
          # https://github.com/wkentaro/labelme
        - Markdown
          # This is a Python implementation of John Gruber's Markdown.
        - matplotlib>=3.5.1
          # Matplotlib is a plotting library for the Python programming language
          # and its numerical mathematics extension NumPy.
        - mediapipe
          # MediaPipe offers ready-to-use yet customizable Python solutions as
          # a prebuilt Python package.
        - munch
          # Munch is a dictionary that supports attribute-style access.
        - mypy
          # Static Typing for Python.
        - multipledispatch
          # A relatively sane approach to multiple dispatch in Python.
        - ninja
          # Ninja is a small build system with a focus on speed.
        - numpy
          # NumPy is the fundamental package for array computing with Python.
        - opencv-python==4.4.0.46
        - opencv-contrib-python==4.4.0.46
        # - opencv-python==4.4.0.46                 ; sys_platform=="win32" or sys_platform=="linux"
        # - opencv-contrib-python==4.4.0.46         ; sys_platform=="win32" or sys_platform=="linux"
        - opencv-python-headless==4.4.0.46        ; sys_platform=="darwin"
        - opencv-contrib-python-headless==4.4.0.46; sys_platform=="darwin"
          # OpenCV library.
        - ordered-enum
          # A small library for adding total orderings to enums.
        - pandas
          # Python Data Analysis Library.
        - Pillow
          # Pillow Image Processing.
        - protobuf
          # Google's data interchange format.
        - pycocotools>=2.0.4
          # Official APIs for the MS-COCO dataset.
        - pydot
          # Python interface to Graphviz's Dot language.
        - PyQt5
          # Qt UI.
        - pytorch-lightning>=1.6.1
          # Pytorch lightning.
        - pyupgrade
        - pyvips
          # A fast image processing library with low memory needs.
          # (https://www.libvips.org/install.html).
        - PyYAML
          # PyYAML features a complete YAML 1.1 parser, Unicode support, pickle
          # support, capable extension API, and sensible error messages.
        - pretrainedmodels
          # Pretrained models for Pytorch (Work in progress).
        - ptflops
          # Flops counter for convolutional networks in pytorch framework.
        - pynvml
          # Provides a Python interface to GPU management and monitoring
          # functions.
        - rawpy
          # Load RAW images, work on their data, and create a postprocessed
          # image.
        - requests
          # Python HTTP for Humans.
        - rich
          # Rich is a Python library for rich text and beautiful formatting in
          # the terminal.
        - scikit-learn
          # Simple and efficient tools for predictive data analysis.
        - scipy
          # SciPy wraps highly-optimized implementations written in low-level
          # languages like Fortran, C, and C++.
        - seaborn
          # Statistical data visualization.
        - sortedcontainers
          # Sorted Containers is an Apache2 licensed sorted collection library,
          # written in pure-Python, and fast as C-extensions.
        - setGPU
          # A small Python library that automatically sets CUDA_VISIBLE_DEVICES
          # to the least-loaded GPU on multi-GPU systems.
        - tensorboard
          # TensorBoard is a tool for providing the measurements and visualizations
          # needed during the machine learning workflow.
        - thop
          # FLOPs computation.
        - timm
          # PyTorch Image Models (timm) is a collection of image models, layers,
          # utilities, optimizers, schedulers, data-loaders / augmentations,
          # and reference training / validation scripts that aim to pull
          # together a wide variety of SOTA models with ability to reproduce
          # ImageNet training results.
        - --extra-index-url https://download.pytorch.org/whl/cu113
        - torch
        - torchvision
        - torchaudio
          # PyTorch.
        - torchmetrics
          # git+https://github.com/PytorchLightning/metrics.git@release/latest
        - torchsummary
          # Model summary in PyTorch.
        - tqdm
          # A Fast, Extensible Progress Bar for Python and CLI.
        - validators
          # Python Data Validation for Humans.
        - wandb
          # Weights & Biases logger.
        - xmltodict
          # `xmltodict` is a Python module that makes working with XML feel
          # like you are working with JSON.
