#
#     /\_____/\
#    /  o   o  \
#   ( ==  ^  == )
#    )         (
#   (           )
#  ( (  )   (  ) )
# (__(__)___(__)__)
#
# Installation:
#   poetry install
#
# References:
#   - pyproject.toml: https://packaging.python.org/en/latest/
#   - poetry        : https://python-poetry.org/docs/
#   - uv            : https://docs.astral.sh/uv/

[project]
name            = "aic26_cross_city"
version         = "1.0.0"
description     = "AI City Challenge 2026 - Track 06: Cross-City Object Detection"
license         = "MIT"
readme          = "README.md"
requires-python = ">=3.13,<3.14"
authors         = [{ name = "Long H. Pham", email = "longpham3105@gmail.com" }]
keywords        = ["computer vision", "deep learning", "research"]
classifiers     = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
]
dependencies    = [
    "mon",
    "cyclopts (>=4.5.1)",               # Intuitive, easy CLIs based on python type hints.
    "hafnia (>=0.7.10)",                # Python SDK for communication with Hafnia platform.
    "jsonlines",
    "jsonlines",                        # A Python library for working with JSON Lines files.
    "lightning",                        # The Deep Learning framework to train, deploy, and ship AI products Lightning fast.
    "nvidia-ml-py (>=13.595.45)",       # To log GPU metrics in tracker
    "rfdetr",                           # RF-DETR: Real-Time SOTA Detection and Segmentation
    "rfdetr-plus",                      # An extension of RF-DETR that unlocks larger, more powerful detection models for when you need the highest possible accuracy.
]

# [project.urls]
# Homepage      = ""
# Documentation = ""
# Repository    = ""
# Issues        = ""

# --- UV SPECIFIC ---
[tool.uv]
package = true
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'"
]

[tool.uv.sources]
mon = { workspace = true }

# --- POETRY SPECIFIC ---
[tool.poetry]
package-mode = false                    # If you want to use Poetry only for dependency management but not for packaging.
# packages = [
    # { include = "edgecrafter", from = "src" }
# ]
include  = []
exclude  = []

[tool.poetry.dependencies]
mon = { path = "../../libs/mon", develop = true }

[build-system]
requires      = ["poetry-core>=2.3.2,<3.0.0"]
build-backend = "poetry.core.masonry.api"
