#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Image Sampling Operations.

This module provides operations for (down-/up-) sampling images.
"""

from __future__ import annotations

__all__ = [
    "pair_downsample",
    "ImageUpsampler",
    "GuidedFilterUpsample",
    "guided_filter_upsample",
    "InterpolationUpsample",
]

from abc import ABC, abstractmethod
from typing import override

import cv2
import torch
from numpy import ndarray
from torch import Tensor
from torch.nn import functional as F
from torchvision.transforms import functional as F_tv, InterpolationMode

from mon import TensorOrArray
from mon.core import Backend, Size, UPSAMPLERS
from .filter import FastGuidedFilter
from .proc import to_image_array, to_image_tensor


# ==============================================================================
# region Functional
# ==============================================================================

def guided_filter_upsample(
    x_lr: Tensor,
    y_hr: Tensor,
    y_lr: Tensor | None = None,
    r: int = 1,
) -> Tensor:
    """Applies the ``FastGuidedFilter`` to upscale an image.

    Args:
        x_lr (Tensor): Low-resolution upscaling image of shape (B, C, H1, W1)
            and values ranging from 0.0 to 1.0.
        y_hr (Tensor): High-resolution guidance image of shape (B, C, H2, W2)
            and values ranging from 0.0 to 1.0.
        y_lr (Tensor, optional): Low-resolution guidance image of shape
            (B, C, H1, W1) and values ranging from 0.0 to 1.0. If None, it will
            be generated by downsampling ``y_hr`` to match the shape of ``x_lr``.
            Defaults to None.
        r (int, optional): Radius of the guided filter. Defaults to 1.

    Returns:
        Tensor: Upscaled image of shape (B, C, H2, W2) and values ranging from
            0.0 to 1.0.
    """
    # Resize y_hr to match x_lr if y_lr is None
    if y_lr is None:
        y_lr = F.interpolate(y_hr, size=x_lr.shape[2:], mode="bilinear", align_corners=False)

    # Move to device
    y_lr = y_lr.to(x_lr.device)
    y_hr = y_hr.to(x_lr.device)

    gf = FastGuidedFilter(r=r)
    x_hr = gf(x_lr, y_lr, y_hr)
    x_hr = x_hr.clamp(0.0, 1.0)
    return x_hr


def pair_downsample(image: Tensor) -> tuple[Tensor, Tensor]:
    """Downsample an image tensor into a pair to half resolution.

    References:
        - Code: https://colab.research.google.com/drive/1i82nyizTdszyHkaHBuKPbWnTzao8HF9b?usp=sharing

    Args:
        image (Tensor): Image tensor of shape (B, C, H, W) and values ranging
            from 0.0 to 1.0.

    Returns:
        tuple[Tensor, Tensor]: Downsampled images of shape (B, C, H/2, W/2).

    Raises:
        TypeError: If ``image`` is not a 4D torch.Tensor.

    Notes:
        Averages diagonal pixels in non-overlapping patches:
            -------------      -------------
            | A1 | B1 | A2 | B2 |      | A1+D1/2 | A2+D2/2 |
            | C1 | D1 | C2 | D2 |      | A3+D3/2 | A4+D4/2 |
            -------------  =>  -------------
            | A3 | B3 | A4 | B4 |      | B1+C1/2 | B2+C2/2 |
            | C3 | D3 | C4 | D4 |      | B3+C3/2 | B4+C4/2 |
            -------------      -------------
    """
    if not isinstance(image, Tensor) or image.ndim != 4:
        raise TypeError(
            f"Expected 'image' to be a 4D tensor, "
            f"but got {image.ndim}D {type(image).__name__},"
        )

    b, c, h, w  = image.shape
    device, dtype = image.device, image.dtype

    # Define kernels: filter_ad picks (top-left, bottom-right), filter_bc picks (top-right, bottom-left)
    # We use .repeat(c, 1, 1, 1) for channel-wise (depthwise) convolution
    kernel_ad = torch.tensor([[[[0.5, 0.0], [0.0, 0.5]]]], device=device, dtype=dtype).repeat(c, 1, 1, 1)
    kernel_bc = torch.tensor([[[[0.0, 0.5], [0.5, 0.0]]]], device=device, dtype=dtype).repeat(c, 1, 1, 1)

    # Stride=2 ensures non-overlapping 2x2 patches
    out_ad = F.conv2d(image, kernel_ad, stride=2, groups=c)
    out_bc = F.conv2d(image, kernel_bc, stride=2, groups=c)
    return out_ad, out_bc

# endregion


# ==============================================================================
# region BASE CLASSES
# ==============================================================================

class ImageUpsampler(ABC):
    """Base class for image upsamplers."""

    # --- Callable & Context Manager ---
    @abstractmethod
    def __call__(
        self,
        x_lr: TensorOrArray,
        y_hr: TensorOrArray,
        y_lr: TensorOrArray | None = None,
        *args, **kwargs
    ) -> TensorOrArray:
        """Upsample the input low-resolution image using the provided
        high-resolution.

        Args:
            x_lr (TensorOrArray): Low-resolution image, formatted as a tensor
                of shape (B, C, H1, W1) and values ranging from 0.0 to 1.0;
                or as an array of shape (H1, W1, C) and values ranging from 0 to 255.
            y_hr (TensorOrArray): High-resolution guidance image, formatted as
                a tensor of shape (B, C, H2, W2) and values ranging from 0.0 to 1.0;
                or as an array of shape (H1, W1, C) and values ranging from 0 to 255.
            y_lr (Tensor, optional): Low-resolution guidance image, formatted
                as a tensor of shape (B, C, H1, W1) and values ranging from 0.0 to 1.0;
                or as an array of shape (H1, W1, C) and values ranging from 0 to 255.
                If None, it will be generated by downsampling ``y_hr`` to match
                the shape of ``x_lr``. Defaults to None.

        Returns:
            TensorOrArray: Upscaled image, formatted as a tensor of shape
                (B, C, H2, W2) and values ranging from 0.0 to 1.0; or as an
                array of shape (H1, W1, C) and values ranging from 0 to 255.
        """
        pass

# endregion


# ==============================================================================
# region CONCRETE IMPLEMENTATIONS
# ==============================================================================

@UPSAMPLERS.register(name="interpolation")
class InterpolationUpsample(ImageUpsampler):
    """Interpolation model for super-resolution."""

    # --- Lifecycle & Initialization ---
    def __init__(self, backend: Backend = Backend.CV2, *args, **kwargs):
        """Initialize a new instance.

        Args:
            backend (Backend, optional): Backend to use for image resizing.
                Can be either 'cv2' for OpenCV or 'torchvision' for PyTorch's
                torchvision. Defaults to Backend.CV2.
            verbose (bool, optional): Verbosity mode. Defaults to True.
        """
        super().__init__()

        # Assign attributes
        self.backend = Backend(backend)

    # --- Callable & Context Manager ---
    @override
    def __call__(self, x_lr: TensorOrArray, imgsz: Size, *args, **kwargs) -> TensorOrArray:
        """Upsample the input low-resolution image using the provided
        high-resolution.

        Args:
            x_lr (TensorOrArray): Low-resolution image, formatted as a tensor
                of shape (B, C, H1, W1) and values ranging from 0.0 to 1.0;
                or as an array of shape (H1, W1, C) and values ranging from 0 to 255.
            imgsz (Size): Size of the high-resolution image.

        Returns:
            TensorOrArray: Upscaled image, formatted as a tensor of shape
                (B, C, H2, W2) and values ranging from 0.0 to 1.0; or as an
                array of shape (H1, W1, C) and values ranging from 0 to 255.
        """
        # Normalize input
        imgsz = Size.from_value(imgsz)

        # 1. Numpy / OpenCV
        if self.backend == Backend.CV2:
            if isinstance(x_lr, Tensor):
                x_lr = to_image_array(x_lr)
            _, _, c = x_lr.shape
            is_depth = (c == 1)
            mode = cv2.INTER_NEAREST if is_depth else cv2.INTER_CUBIC
            x_hr = cv2.resize(src=x_lr, dsize=imgsz.wh, interpolation=mode)

        # 2. Tensor / TorchVision
        elif self.backend == Backend.TORCHVISION:
            if isinstance(x_lr, ndarray):
                x_lr = to_image_tensor(x_lr)
            _, c, _, _ = x_lr.shape
            is_depth = (c == 1)
            mode = InterpolationMode.NEAREST_EXACT if is_depth else InterpolationMode.BICUBIC
            x_hr = F_tv.resize(
                img=x_lr,
                size=list(imgsz.hw),
                interpolation=mode,
                antialias=False,
            )

        # 3. Error: Unsupported backend
        else:
            raise ValueError(
                f"Expected 'x_lr' to be a tensor or ndarray, "
                f"but got {type(x_lr).__name__}."
            )

        return x_hr


@UPSAMPLERS.register(name="guided_filter")
class GuidedFilterUpsample(ImageUpsampler):
    """Guided Filter Upsample model for super-resolution tasks."""

    # --- Lifecycle & Initialization ---
    def __init__(self, radius: int = 1, *args, **kwargs):
        """Initialize a new instance.

        Args:
            radius (int, optional): Radius for the guided filter. Defaults to 1.
        """
        super().__init__()

        # Assign attributes
        self.radius = radius

    # --- Callable & Context Manager ---
    @override
    def __call__(
        self,
        x_lr: Tensor,
        y_hr: Tensor,
        y_lr: Tensor | None = None,
        *args, **kwargs
    ) -> TensorOrArray:
        """Upsample the input low-resolution image using the provided
        high-resolution.

        Args:
            x_lr (Tensor): Low-resolution upscaling image of shape (B, C, H1, W1)
                and values ranging from 0.0 to 1.0.
            y_hr (Tensor): High-resolution guidance image of shape (B, C, H2, W2)
                and values ranging from 0.0 to 1.0.
            y_lr (Tensor, optional): Low-resolution guidance image of shape
                (B, C, H1, W1) and values ranging from 0.0 to 1.0. If None, it will
                be generated by downsampling ``y_hr`` to match the shape of ``x_lr``.
                Defaults to None.

        Returns:
            Tensor: Upscaled image of shape (B, C, H2, W2) and values ranging
                from 0.0 to 1.0.
        """
        return guided_filter_upsample(x_lr=x_lr, y_lr=y_lr, y_hr=y_hr, r=self.radius)

# endregion


# ==============================================================================
# region UNIT TEST
# ==============================================================================

if __name__ == "__main__":
    pass

# endregion
