#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""A package for core data and functionalities.

This package contains modules that provide core data types, utilities, and
functionalities used throughout the project. It serves as a foundational layer
for handling various data types, device management, logging, configuration
parsing, and other essential operations.
"""

__all__ = [
    # Flat exposed APIs
    "ALBUMENTATIONS",
    "ActiveLearningPhase",
    "AppleRGB",
    "BBoxFormat",
    "CLI_OPTIONS",
    "ConfigExtension",
    "DATASETS",
    "DEFAULT_ARGS",
    "DEPTH_SOURCE",
    "DepthSource",
    "Enum",
    "Factory",
    "INFRARED_SOURCE",
    "ImageExtension",
    "InfraredSource",
    "MLType",
    "MODELS",
    "MemoryUnit",
    "ModelFactory",
    "Path",
    "PosixPath",
    "PurePath",
    "PurePosixPath",
    "PureWindowsPath",
    "RGB",
    "RGB12",
    "ROOT_DIR",
    "RunCLI",
    "RunMode",
    "SAVE_CKPT_EXT",
    "SAVE_DEBUG_DIR",
    "SAVE_IMAGE_DIR",
    "SAVE_IMAGE_EXT",
    "SAVE_LABEL_DIR",
    "SAVE_VISUALIZE_DIR",
    "SAVE_WEIGHTS_EXT",
    "Split",
    "TRTPrecision",
    "Task",
    "TimeProfiler",
    "Timer",
    "TrackState",
    "VERBOSE",
    "VideoExtension",
    "WeightExtension",
    "WindowsPath",
    "ZOO_DIR",
    "camelize",
    "clear_terminal",
    "console",
    "create_combinations",
    "create_device",
    "create_download_bar",
    "create_progress_bar",
    "decamelize",
    "dekebabize",
    "depascalize",
    "disable_print",
    "download_url_to_file",
    "enable_print",
    "error_console",
    "get_cuda_memory_usages",
    "get_memory_usages",
    "get_model_device",
    "is_camelcase",
    "is_float",
    "is_int",
    "is_kebabcase",
    "is_pascalcase",
    "is_snakecase",
    "kebabize",
    "list_archs",
    "list_config_files",
    "list_datasets",
    "list_devices",
    "list_models",
    "list_weights_files",
    "load_config",
    "load_project_defaults",
    "log",
    "log_error",
    "logger",
    "merge_dicts",
    "parse_cli_args",
    "parse_config_file",
    "parse_data_dir",
    "parse_default_args",
    "parse_device",
    "parse_model_dir",
    "parse_model_fullname",
    "parse_output_dir",
    "parse_predict_args",
    "parse_save_dir",
    "parse_train_args",
    "parse_weights_dir",
    "parse_weights_file",
    "parse_weights_from_config",
    "pascalize",
    "pprint_dict",
    "print_run_summary",
    "pynvml_available",
    "rprint_dict",
    "rprint_list_dicts",
    "set_random_seed",
    "snakecase",
    "sort",
    "to_float",
    "to_float_list",
    "to_int",
    "to_int_list",
    "to_list",
    "to_ntuple",
    "to_str",
    "unique",
    # Hierarchical exposed APIs
    "bbox",
    "contour",
    "depth",
    "dtypes",
    "image",
    "instance",
    "mask",
    "probs",
    "thermal",
    "video",
]  # Public API

from .console import (
    console,
    error_console,
    log,
    log_error,
    pprint_dict,
    rprint_dict,
    rprint_list_dicts,
)
from .constants import (
    DEPTH_SOURCE,
    INFRARED_SOURCE,
    ROOT_DIR,
    SAVE_CKPT_EXT,
    SAVE_DEBUG_DIR,
    SAVE_IMAGE_DIR,
    SAVE_IMAGE_EXT,
    SAVE_LABEL_DIR,
    SAVE_VISUALIZE_DIR,
    SAVE_WEIGHTS_EXT,
    VERBOSE,
    ZOO_DIR,
)
from .device import (
    create_device,
    get_cuda_memory_usages,
    get_memory_usages,
    get_model_device,
    list_devices,
    parse_device,
    pynvml_available,
)
from .dtypes import (
    bbox,
    contour,
    depth,
    image,
    instance,
    mask,
    probs,
    thermal,
    video,
)
from .enum import (
    ActiveLearningPhase,
    AppleRGB,
    BBoxFormat,
    ConfigExtension,
    DepthSource,
    Enum,
    ImageExtension,
    InfraredSource,
    MemoryUnit,
    MLType,
    RGB,
    RGB12,
    RunMode,
    Split,
    Task,
    TrackState,
    TRTPrecision,
    VideoExtension,
    WeightExtension,
)
from .factory import ALBUMENTATIONS, DATASETS, Factory, ModelFactory, MODELS
from .logging import disable_print, enable_print, logger
from .pathlib import (
    download_url_to_file,
    Path,
    PosixPath,
    PurePath,
    PurePosixPath,
    PureWindowsPath,
    WindowsPath,
)
from .rich import create_download_bar, create_progress_bar
from .runtime import (
    CLI_OPTIONS,
    DEFAULT_ARGS,
    list_archs,
    list_config_files,
    list_datasets,
    list_models,
    list_weights_files,
    load_config,
    load_project_defaults,
    parse_cli_args,
    parse_config_file,
    parse_data_dir,
    parse_default_args,
    parse_model_dir,
    parse_model_fullname,
    parse_output_dir,
    parse_predict_args,
    parse_save_dir,
    parse_train_args,
    parse_weights_dir,
    parse_weights_file,
    parse_weights_from_config,
    print_run_summary,
    RunCLI,
)
from .system import clear_terminal, set_random_seed
from .timer import TimeProfiler, Timer
from .utils import (
    camelize,
    create_combinations,
    decamelize,
    dekebabize,
    depascalize,
    is_camelcase,
    is_float,
    is_int,
    is_kebabcase,
    is_pascalcase,
    is_snakecase,
    kebabize,
    merge_dicts,
    pascalize,
    snakecase,
    sort,
    to_float,
    to_float_list,
    to_int,
    to_int_list,
    to_list,
    to_ntuple,
    to_str,
    unique,
)
